// Default card data - 100 cards
export const defaultCards = [
    {"name":"2B","element":"Neutral","hairColor":"White/Silver","type":"Non-Human","hp":"80","atk":"97","def":"66","spd":"82","talents":"","notes":""},
    {"name":"9S","element":"Neutral","hairColor":"White/Silver","type":"Non-Human","hp":"94","atk":"67","def":"90","spd":"76","talents":"","notes":""},
    {"name":"Abel Walker","element":"Dark","hairColor":"Blonde","type":"Human","hp":"79","atk":"100","def":"80","spd":"81","talents":"","notes":""},
    {"name":"Accelerator","element":"Light","hairColor":"White","type":"Human","hp":"73","atk":"89","def":"70","spd":"89","talents":"","notes":""},
    {"name":"Acnologia","element":"Neutral","hairColor":"Blue","type":"Non-Human","hp":"84","atk":"77","def":"93","spd":"73","talents":"","notes":""},
    {"name":"Adam","element":"Light","hairColor":"Blonde","type":"Human","hp":"93","atk":"77","def":"76","spd":"84","talents":"","notes":""},
    {"name":"Adam Smasher","element":"Dark","hairColor":"Bald","type":"Non-Human","hp":"98","atk":"98","def":"70","spd":"70","talents":"","notes":""},
    {"name":"Ai Hoshino","element":"Light","hairColor":"Purple","type":"Human","hp":"82","atk":"80","def":"90","spd":"81","talents":"","notes":""},
    {"name":"Ainz Ooal Gown","element":"Dark","hairColor":"None (Skeleton)","type":"Non-Human","hp":"82","atk":"99","def":"66","spd":"78","talents":"","notes":""},
    {"name":"Aira Shiratori","element":"Light","hairColor":"Black","type":"Human","hp":"95","atk":"80","def":"60","spd":"98","talents":"","notes":""},
    {"name":"Airi Sakura","element":"Water","hairColor":"Pink","type":"Human","hp":"72","atk":"78","def":"91","spd":"93","talents":"","notes":""},
    {"name":"Ais Wallenstein","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"68","atk":"93","def":"94","spd":"66","talents":"","notes":""},
    {"name":"Akame","element":"Dark","hairColor":"Black","type":"Human","hp":"85","atk":"80","def":"69","spd":"86","talents":"","notes":""},
    {"name":"Akane Kurokawa","element":"Water","hairColor":"Black","type":"Human","hp":"94","atk":"76","def":"82","spd":"81","talents":"","notes":""},
    {"name":"Akane Tsunemori","element":"Light","hairColor":"Brown","type":"Human","hp":"77","atk":"89","def":"93","spd":"62","talents":"","notes":""},
    {"name":"Aki Hayakawa","element":"Dark","hairColor":"Black","type":"Human","hp":"79","atk":"94","def":"76","spd":"80","talents":"","notes":""},
    {"name":"Akiko Yosano","element":"Neutral","hairColor":"Black","type":"Human","hp":"85","atk":"75","def":"85","spd":"80","talents":"","notes":""},
    {"name":"Akutarou Shindo","element":"Water","hairColor":"","type":"Human","hp":"79","atk":"99","def":"79","spd":"82","talents":"","notes":"?"},
    {"name":"Aladdin","element":"Light","hairColor":"Blue","type":"Non-Human","hp":"64","atk":"76","def":"84","spd":"97","talents":"","notes":""},
    {"name":"Albedo","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"96","atk":"94","def":"67","spd":"67","talents":"","notes":""},
    {"name":"Alex Louis Armstrong","element":"Light","hairColor":"Blonde","type":"Human","hp":"89","atk":"87","def":"92","spd":"86","talents":"","notes":""},
    {"name":"Alger Wilson","element":"Water","hairColor":"Dark Blue","type":"Human","hp":"101","atk":"83","def":"95","spd":"60","talents":"","notes":""},
    {"name":"Alice Zuberg","element":"Light","hairColor":"Blonde","type":"Human","hp":"75","atk":"86","def":"98","spd":"65","talents":"","notes":""},
    {"name":"All Might","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"85","atk":"94","def":"76","spd":"67","talents":"","notes":""},
    {"name":"Alpha","element":"Dark","hairColor":"Black","type":"Human","hp":"86","atk":"79","def":"85","spd":"80","talents":"","notes":""},
    {"name":"Amber","element":"Neutral","hairColor":"Black","type":"Human","hp":"79","atk":"99","def":"83","spd":"66","talents":"","notes":""},
    {"name":"Ami Mizuno (Sailor Mercury)","element":"Water","hairColor":"Blue","type":"Human","hp":"72","atk":"84","def":"70","spd":"98","talents":"","notes":""},
    {"name":"Amiya","element":"Dark","hairColor":"Brown","type":"Non-Human","hp":"80","atk":"93","def":"92","spd":"72","talents":"","notes":""},
    {"name":"Angel Devil","element":"Neutral","hairColor":"Red/Orange","type":"Non-Human","hp":"88","atk":"91","def":"73","spd":"76","talents":"","notes":""},
    {"name":"Anna Kyoyama","element":"Light","hairColor":"Blonde","type":"Human","hp":"76","atk":"89","def":"80","spd":"84","talents":"","notes":""},
    {"name":"Annie Leonhart","element":"Water","hairColor":"Blonde","type":"Human","hp":"96","atk":"96","def":"65","spd":"70","talents":"","notes":""},
    {"name":"Anya Forger","element":"Light","hairColor":"Pink","type":"Human","hp":"80","atk":"80","def":"80","spd":"80","talents":"","notes":""},
    {"name":"Aoba Kuronuma","element":"Water","hairColor":"Dark Blue","type":"Human","hp":"87","atk":"87","def":"92","spd":"74","talents":"","notes":""},
    {"name":"Aoi Asahina","element":"Water","hairColor":"Brown","type":"Human","hp":"72","atk":"77","def":"91","spd":"87","talents":"","notes":""},
    {"name":"Aoi Todo","element":"Water","hairColor":"Black","type":"Human","hp":"85","atk":"92","def":"73","spd":"76","talents":"","notes":""},
    {"name":"Aomine Daiki","element":"Water","hairColor":"Navy Blue","type":"Human","hp":"79","atk":"88","def":"89","spd":"84","talents":"","notes":""},
    {"name":"Aqua","element":"Water","hairColor":"Blue","type":"Non-Human","hp":"80","atk":"93","def":"85","spd":"68","talents":"","notes":""},
    {"name":"Aquamarine Hoshino","element":"Water","hairColor":"Blonde","type":"Human","hp":"86","atk":"85","def":"89","spd":"76","talents":"","notes":""},
    {"name":"Arataka Reigen","element":"Neutral","hairColor":"Brown","type":"Human","hp":"85","atk":"70","def":"87","spd":"75","talents":"","notes":""},
    {"name":"Artoria Pendragon","element":"Light","hairColor":"Blonde","type":"Human","hp":"86","atk":"93","def":"75","spd":"65","talents":"","notes":""},
    {"name":"Aru Akise","element":"Light","hairColor":"White/Silver","type":"Non-Human","hp":"95","atk":"84","def":"70","spd":"76","talents":"","notes":""},
    {"name":"Ash Ketchum","element":"Neutral","hairColor":"Black","type":"Human","hp":"85","atk":"90","def":"79","spd":"80","talents":"","notes":""},
    {"name":"Asia Argento","element":"Light","hairColor":"Blonde","type":"Human","hp":"99","atk":"81","def":"62","spd":"81","talents":"","notes":""},
    {"name":"Askeladd","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"88","atk":"90","def":"70","spd":"88","talents":"","notes":""},
    {"name":"Asta","element":"Dark","hairColor":"Gray/Silver","type":"Human","hp":"83","atk":"85","def":"68","spd":"93","talents":"","notes":""},
    {"name":"Astolfo","element":"Neutral","hairColor":"Pink","type":"Human","hp":"70","atk":"82","def":"86","spd":"93","talents":"","notes":""},
    {"name":"Asuna Yuuki","element":"Water","hairColor":"Brown","type":"Human","hp":"97","atk":"85","def":"63","spd":"79","talents":"","notes":""},
    {"name":"Atom","element":"Neutral","hairColor":"Black","type":"Non-Human","hp":"80","atk":"98","def":"65","spd":"95","talents":"","notes":""},
    {"name":"Atsushi Nakajima","element":"Light","hairColor":"White/Silver","type":"Human","hp":"90","atk":"81","def":"93","spd":"63","talents":"","notes":""},
    {"name":"Audrey Hall","element":"Light","hairColor":"Blonde","type":"Human","hp":"99","atk":"80","def":"94","spd":"66","talents":"","notes":""},
    {"name":"Aura","element":"Dark","hairColor":"Purple","type":"Non-Human","hp":"81","atk":"90","def":"81","spd":"82","talents":"","notes":""},
    {"name":"Aura Bella Fiora","element":"Light","hairColor":"","type":"","hp":"75","atk":"90","def":"82","spd":"91","talents":"","notes":"?"},
    {"name":"Ayato Kirishima","element":"Dark","hairColor":"Purple","type":"Non-Human","hp":"87","atk":"94","def":"63","spd":"75","talents":"","notes":""},
    {"name":"Ayato Naoi","element":"Neutral","hairColor":"Red/Orange","type":"Human","hp":"89","atk":"81","def":"86","spd":"67","talents":"","notes":""},
    {"name":"Azik Eggers","element":"Neutral","hairColor":"Black","type":"Human","hp":"89","atk":"95","def":"73","spd":"83","talents":"","notes":""},
    {"name":"Azusa Nakano","element":"Light","hairColor":"Black","type":"Human","hp":"80","atk":"80","def":"82","spd":"77","talents":"","notes":""},
    {"name":"Baki Hanma","element":"Light","hairColor":"Black","type":"Human","hp":"89","atk":"82","def":"80","spd":"75","talents":"","notes":""},
    {"name":"Ban","element":"Dark","hairColor":"Blue/White","type":"Human","hp":"90","atk":"61","def":"83","spd":"94","talents":"","notes":""},
    {"name":"Basara Toujou","element":"Light","hairColor":"Brown","type":"Non-Human","hp":"65","atk":"77","def":"94","spd":"87","talents":"","notes":""},
    {"name":"Batman","element":"Dark","hairColor":"Black","type":"Human","hp":"90","atk":"85","def":"85","spd":"76","talents":"","notes":""},
    {"name":"Beatrix","element":"Light","hairColor":"Blonde","type":"Human","hp":"73","atk":"75","def":"102","spd":"89","talents":"","notes":""},
    {"name":"Bebin","element":"Neutral","hairColor":"Black","type":"Human","hp":"86","atk":"86","def":"83","spd":"85","talents":"","notes":""},
    {"name":"Beerus","element":"Light","hairColor":"Purple/None","type":"Non-Human","hp":"81","atk":"88","def":"90","spd":"70","talents":"","notes":""},
    {"name":"Bell Cranel","element":"Dark","hairColor":"White","type":"Human","hp":"75","atk":"88","def":"86","spd":"70","talents":"","notes":""},
    {"name":"Bell Hydra","element":"Neutral","hairColor":"Black","type":"Non-Human","hp":"84","atk":"89","def":"66","spd":"82","talents":"","notes":""},
    {"name":"Benedict Blue","element":"Water","hairColor":"Blonde","type":"Human","hp":"95","atk":"87","def":"68","spd":"80","talents":"","notes":""},
    {"name":"Benson Moretti","element":"Neutral","hairColor":"","type":"","hp":"78","atk":"103","def":"85","spd":"74","talents":"","notes":"?"},
    {"name":"Beros","element":"Dark","hairColor":"Pink","type":"Non-Human","hp":"84","atk":"86","def":"80","spd":"76","talents":"","notes":""},
    {"name":"Beta","element":"Dark","hairColor":"Blonde","type":"Human","hp":"80","atk":"81","def":"95","spd":"82","talents":"","notes":""},
    {"name":"Biscuit Oliva","element":"Light","hairColor":"Black","type":"Human","hp":"82","atk":"90","def":"73","spd":"76","talents":"","notes":""},
    {"name":"Bisky Krueger","element":"Light","hairColor":"Pink/Blonde","type":"Human","hp":"67","atk":"96","def":"62","spd":"95","talents":"","notes":""},
    {"name":"Blair","element":"Dark","hairColor":"Purple","type":"Non-Human","hp":"102","atk":"69","def":"68","spd":"84","talents":"","notes":""},
    {"name":"Blake Belladonna","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"80","atk":"96","def":"80","spd":"81","talents":"","notes":""},
    {"name":"Blood Red Commander Igris","element":"Neutral","hairColor":"None","type":"Non-Human","hp":"90","atk":"81","def":"84","spd":"85","talents":"","notes":""},
    {"name":"Bond Forger","element":"Neutral","hairColor":"White (Fur)","type":"Non-Human","hp":"83","atk":"89","def":"80","spd":"87","talents":"","notes":""},
    {"name":"Botan","element":"Light","hairColor":"Blue","type":"Non-Human","hp":"92","atk":"73","def":"81","spd":"81","talents":"","notes":""},
    {"name":"Braz D Blood","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"70","atk":"92","def":"87","spd":"75","talents":"","notes":""},
    {"name":"Brook","element":"Dark","hairColor":"Black Afro","type":"Non-Human","hp":"78","atk":"94","def":"72","spd":"79","talents":"","notes":""},
    {"name":"Brunhilde","element":"Neutral","hairColor":"White/Silver","type":"Non-Human","hp":"90","atk":"87","def":"78","spd":"72","talents":"","notes":""},
    {"name":"Buddha","element":"Light","hairColor":"Blonde","type":"Non-Human","hp":"80","atk":"74","def":"91","spd":"81","talents":"","notes":""},
    {"name":"Byakuya Togami","element":"Light","hairColor":"Blonde","type":"Human","hp":"89","atk":"70","def":"91","spd":"75","talents":"","notes":""},
    {"name":"Canute","element":"Water","hairColor":"Blonde","type":"Human","hp":"76","atk":"94","def":"80","spd":"89","talents":"","notes":""},
    {"name":"C.C.","element":"Light","hairColor":"Green","type":"Human","hp":"95","atk":"67","def":"93","spd":"70","talents":"","notes":"?"},
    {"name":"Celestia Ludenberg","element":"Dark","hairColor":"Black","type":"Human","hp":"91","atk":"70","def":"78","spd":"89","talents":"","notes":""},
    {"name":"Celty Sturluson","element":"Dark","hairColor":"None (Headless)","type":"Non-Human","hp":"103","atk":"82","def":"78","spd":"74","talents":"","notes":""},
    {"name":"Chainsaw Man","element":"Dark","hairColor":"Orange/Blonde","type":"Non-Human","hp":"69","atk":"102","def":"86","spd":"69","talents":"","notes":""},
    {"name":"Charmy Pappitson","element":"Dark","hairColor":"White/Silver","type":"Non-Human","hp":"82","atk":"87","def":"79","spd":"77","talents":"","notes":""},
    {"name":"Chifuyu Matsuno","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"86","atk":"75","def":"93","spd":"73","talents":"","notes":""},
    {"name":"Chihiro Ogino","element":"Light","hairColor":"Brown","type":"Human","hp":"100","atk":"70","def":"100","spd":"70","talents":"","notes":""},
    {"name":"Chika Fujiwara","element":"Light","hairColor":"Pink","type":"Human","hp":"87","atk":"90","def":"82","spd":"66","talents":"","notes":""},
    {"name":"Child Emperor","element":"Neutral","hairColor":"Brown","type":"Human","hp":"84","atk":"85","def":"62","spd":"93","talents":"","notes":""},
    {"name":"Chino Kafuu","element":"Water","hairColor":"Blue","type":"Human","hp":"80","atk":"95","def":"81","spd":"70","talents":"","notes":""},
    {"name":"Chisato Hasegawa","element":"Neutral","hairColor":"Brown","type":"Human","hp":"98","atk":"92","def":"64","spd":"70","talents":"","notes":"?"},
    {"name":"Chiya Ujimatsu","element":"Water","hairColor":"Purple","type":"Human","hp":"76","atk":"69","def":"98","spd":"77","talents":"","notes":""},
    {"name":"Chlammy Zell","element":"Neutral","hairColor":"White/Silver","type":"Human","hp":"81","atk":"81","def":"81","spd":"81","talents":"","notes":""},
    {"name":"Choji Tomiyama","element":"Dark","hairColor":"","type":"","hp":"84","atk":"94","def":"85","spd":"77","talents":"","notes":"?"},
    {"name":"Chomusuke","element":"Dark","hairColor":"Black (Fur)","type":"Non-Human","hp":"81","atk":"81","def":"81","spd":"81","talents":"","notes":""},
    {"name":"Choso","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"85","atk":"80","def":"91","spd":"65","talents":"","notes":""},
    {"name":"Chuuya Nakahara","element":"Dark","hairColor":"Orange/Red","type":"Human","hp":"70","atk":"89","def":"82","spd":"89","talents":"","notes":""},
    {"name":"Cid Kagenou","element":"Dark","hairColor":"Black","type":"Human","hp":"82","atk":"85","def":"82","spd":"86","talents":"","notes":""}
];
