// Default card data - 100 cards
export const defaultCards = [
    {"name":"2B","element":"Neutral","hairColor":"White/Silver","type":"Non-Human","hp":"80","atk":"97","def":"66","spd":"82","talents":"","notes":""},
    {"name":"9S","element":"Neutral","hairColor":"White/Silver","type":"Non-Human","hp":"94","atk":"67","def":"90","spd":"76","talents":"","notes":""},
    {"name":"Abel Walker","element":"Dark","hairColor":"Blonde","type":"Human","hp":"79","atk":"100","def":"80","spd":"81","talents":"","notes":""},
    {"name":"Accelerator","element":"Light","hairColor":"White","type":"Human","hp":"73","atk":"89","def":"70","spd":"89","talents":"","notes":""},
    {"name":"Acnologia","element":"Neutral","hairColor":"Blue","type":"Non-Human","hp":"84","atk":"77","def":"93","spd":"73","talents":"","notes":""},
    {"name":"Adam","element":"Light","hairColor":"Blonde","type":"Human","hp":"93","atk":"77","def":"76","spd":"84","talents":"","notes":""},
    {"name":"Adam Smasher","element":"Dark","hairColor":"Bald","type":"Non-Human","hp":"98","atk":"98","def":"70","spd":"70","talents":"","notes":""},
    {"name":"Ai Hoshino","element":"Light","hairColor":"Purple","type":"Human","hp":"82","atk":"80","def":"90","spd":"81","talents":"","notes":""},
    {"name":"Ainz Ooal Gown","element":"Dark","hairColor":"None (Skeleton)","type":"Non-Human","hp":"82","atk":"99","def":"66","spd":"78","talents":"","notes":""},
    {"name":"Aira Shiratori","element":"Light","hairColor":"Black","type":"Human","hp":"95","atk":"80","def":"60","spd":"98","talents":"","notes":""},
    {"name":"Airi Sakura","element":"Water","hairColor":"Pink","type":"Human","hp":"72","atk":"78","def":"91","spd":"93","talents":"","notes":""},
    {"name":"Ais Wallenstein","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"68","atk":"93","def":"94","spd":"66","talents":"","notes":""},
    {"name":"Akame","element":"Dark","hairColor":"Black","type":"Human","hp":"85","atk":"80","def":"69","spd":"86","talents":"","notes":""},
    {"name":"Akane Kurokawa","element":"Water","hairColor":"Black","type":"Human","hp":"94","atk":"76","def":"82","spd":"81","talents":"","notes":""},
    {"name":"Akane Tsunemori","element":"Light","hairColor":"Brown","type":"Human","hp":"77","atk":"89","def":"93","spd":"62","talents":"","notes":""},
    {"name":"Aki Hayakawa","element":"Dark","hairColor":"Black","type":"Human","hp":"79","atk":"94","def":"76","spd":"80","talents":"","notes":""},
    {"name":"Akiko Yosano","element":"Neutral","hairColor":"Black","type":"Human","hp":"85","atk":"75","def":"85","spd":"80","talents":"","notes":""},
    {"name":"Akutarou Shindo","element":"Water","hairColor":"","type":"Human","hp":"79","atk":"99","def":"79","spd":"82","talents":"","notes":"?"},
    {"name":"Aladdin","element":"Light","hairColor":"Blue","type":"Non-Human","hp":"64","atk":"76","def":"84","spd":"97","talents":"","notes":""},
    {"name":"Albedo","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"96","atk":"94","def":"67","spd":"67","talents":"","notes":""},
    {"name":"Alex Louis Armstrong","element":"Light","hairColor":"Blonde","type":"Human","hp":"89","atk":"87","def":"92","spd":"86","talents":"","notes":""},
    {"name":"Alger Wilson","element":"Water","hairColor":"Dark Blue","type":"Human","hp":"101","atk":"83","def":"95","spd":"60","talents":"","notes":""},
    {"name":"Alice Zuberg","element":"Light","hairColor":"Blonde","type":"Human","hp":"75","atk":"86","def":"98","spd":"65","talents":"","notes":""},
    {"name":"All Might","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"85","atk":"94","def":"76","spd":"67","talents":"","notes":""},
    {"name":"Alpha","element":"Dark","hairColor":"Black","type":"Human","hp":"86","atk":"79","def":"85","spd":"80","talents":"","notes":""},
    {"name":"Amber","element":"Neutral","hairColor":"Black","type":"Human","hp":"79","atk":"99","def":"83","spd":"66","talents":"","notes":""},
    {"name":"Ami Mizuno (Sailor Mercury)","element":"Water","hairColor":"Blue","type":"Human","hp":"72","atk":"84","def":"70","spd":"98","talents":"","notes":""},
    {"name":"Amiya","element":"Dark","hairColor":"Brown","type":"Non-Human","hp":"80","atk":"93","def":"92","spd":"72","talents":"","notes":""},
    {"name":"Angel Devil","element":"Neutral","hairColor":"Red/Orange","type":"Non-Human","hp":"88","atk":"91","def":"73","spd":"76","talents":"","notes":""},
    {"name":"Anna Kyoyama","element":"Light","hairColor":"Blonde","type":"Human","hp":"76","atk":"89","def":"80","spd":"84","talents":"","notes":""},
    {"name":"Annie Leonhart","element":"Water","hairColor":"Blonde","type":"Human","hp":"96","atk":"96","def":"65","spd":"70","talents":"","notes":""},
    {"name":"Anya Forger","element":"Light","hairColor":"Pink","type":"Human","hp":"80","atk":"80","def":"80","spd":"80","talents":"","notes":""},
    {"name":"Aoba Kuronuma","element":"Water","hairColor":"Dark Blue","type":"Human","hp":"87","atk":"87","def":"92","spd":"74","talents":"","notes":""},
    {"name":"Aoi Asahina","element":"Water","hairColor":"Brown","type":"Human","hp":"72","atk":"77","def":"91","spd":"87","talents":"","notes":""},
    {"name":"Aoi Todo","element":"Water","hairColor":"Black","type":"Human","hp":"85","atk":"92","def":"73","spd":"76","talents":"","notes":""},
    {"name":"Aomine Daiki","element":"Water","hairColor":"Navy Blue","type":"Human","hp":"79","atk":"88","def":"89","spd":"84","talents":"","notes":""},
    {"name":"Aqua","element":"Water","hairColor":"Blue","type":"Non-Human","hp":"80","atk":"93","def":"85","spd":"68","talents":"","notes":""},
    {"name":"Aquamarine Hoshino","element":"Water","hairColor":"Blonde","type":"Human","hp":"86","atk":"85","def":"89","spd":"76","talents":"","notes":""},
    {"name":"Arataka Reigen","element":"Neutral","hairColor":"Brown","type":"Human","hp":"85","atk":"70","def":"87","spd":"75","talents":"","notes":""},
    {"name":"Artoria Pendragon","element":"Light","hairColor":"Blonde","type":"Human","hp":"86","atk":"93","def":"75","spd":"65","talents":"","notes":""},
    {"name":"Aru Akise","element":"Light","hairColor":"White/Silver","type":"Non-Human","hp":"95","atk":"84","def":"70","spd":"76","talents":"","notes":""},
    {"name":"Ash Ketchum","element":"Neutral","hairColor":"Black","type":"Human","hp":"85","atk":"90","def":"79","spd":"80","talents":"","notes":""},
    {"name":"Asia Argento","element":"Light","hairColor":"Blonde","type":"Human","hp":"99","atk":"81","def":"62","spd":"81","talents":"","notes":""},
    {"name":"Askeladd","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"88","atk":"90","def":"70","spd":"88","talents":"","notes":""},
    {"name":"Asta","element":"Dark","hairColor":"Gray/Silver","type":"Human","hp":"83","atk":"85","def":"68","spd":"93","talents":"","notes":""},
    {"name":"Astolfo","element":"Neutral","hairColor":"Pink","type":"Human","hp":"70","atk":"82","def":"86","spd":"93","talents":"","notes":""},
    {"name":"Asuna Yuuki","element":"Water","hairColor":"Brown","type":"Human","hp":"97","atk":"85","def":"63","spd":"79","talents":"","notes":""},
    {"name":"Atom","element":"Neutral","hairColor":"Black","type":"Non-Human","hp":"80","atk":"98","def":"65","spd":"95","talents":"","notes":""},
    {"name":"Atsushi Nakajima","element":"Light","hairColor":"White/Silver","type":"Human","hp":"90","atk":"81","def":"93","spd":"63","talents":"","notes":""},
    {"name":"Audrey Hall","element":"Light","hairColor":"Blonde","type":"Human","hp":"99","atk":"80","def":"94","spd":"66","talents":"","notes":""},
    {"name":"Aura","element":"Dark","hairColor":"Purple","type":"Non-Human","hp":"81","atk":"90","def":"81","spd":"82","talents":"","notes":""},
    {"name":"Aura Bella Fiora","element":"Light","hairColor":"","type":"","hp":"75","atk":"90","def":"82","spd":"91","talents":"","notes":"?"},
    {"name":"Ayato Kirishima","element":"Dark","hairColor":"Purple","type":"Non-Human","hp":"87","atk":"94","def":"63","spd":"75","talents":"","notes":""},
    {"name":"Ayato Naoi","element":"Neutral","hairColor":"Red/Orange","type":"Human","hp":"89","atk":"81","def":"86","spd":"67","talents":"","notes":""},
    {"name":"Azik Eggers","element":"Neutral","hairColor":"Black","type":"Human","hp":"89","atk":"95","def":"73","spd":"83","talents":"","notes":""},
    {"name":"Azusa Nakano","element":"Light","hairColor":"Black","type":"Human","hp":"80","atk":"80","def":"82","spd":"77","talents":"","notes":""},
    {"name":"Baki Hanma","element":"Light","hairColor":"Black","type":"Human","hp":"89","atk":"82","def":"80","spd":"75","talents":"","notes":""},
    {"name":"Ban","element":"Dark","hairColor":"Blue/White","type":"Human","hp":"90","atk":"61","def":"83","spd":"94","talents":"","notes":""},
    {"name":"Basara Toujou","element":"Light","hairColor":"Brown","type":"Non-Human","hp":"65","atk":"77","def":"94","spd":"87","talents":"","notes":""},
    {"name":"Batman","element":"Dark","hairColor":"Black","type":"Human","hp":"90","atk":"85","def":"85","spd":"76","talents":"","notes":""},
    {"name":"Beatrix","element":"Light","hairColor":"Blonde","type":"Human","hp":"73","atk":"75","def":"102","spd":"89","talents":"","notes":""},
    {"name":"Bebin","element":"Neutral","hairColor":"Black","type":"Human","hp":"86","atk":"86","def":"83","spd":"85","talents":"","notes":""},
    {"name":"Beerus","element":"Light","hairColor":"Purple/None","type":"Non-Human","hp":"81","atk":"88","def":"90","spd":"70","talents":"","notes":""},
    {"name":"Bell Cranel","element":"Dark","hairColor":"White","type":"Human","hp":"75","atk":"88","def":"86","spd":"70","talents":"","notes":""},
    {"name":"Bell Hydra","element":"Neutral","hairColor":"Black","type":"Non-Human","hp":"84","atk":"89","def":"66","spd":"82","talents":"","notes":""},
    {"name":"Benedict Blue","element":"Water","hairColor":"Blonde","type":"Human","hp":"95","atk":"87","def":"68","spd":"80","talents":"","notes":""},
    {"name":"Benson Moretti","element":"Neutral","hairColor":"","type":"","hp":"78","atk":"103","def":"85","spd":"74","talents":"","notes":"?"},
    {"name":"Beros","element":"Dark","hairColor":"Pink","type":"Non-Human","hp":"84","atk":"86","def":"80","spd":"76","talents":"","notes":""},
    {"name":"Beta","element":"Dark","hairColor":"Blonde","type":"Human","hp":"80","atk":"81","def":"95","spd":"82","talents":"","notes":""},
    {"name":"Biscuit Oliva","element":"Light","hairColor":"Black","type":"Human","hp":"82","atk":"90","def":"73","spd":"76","talents":"","notes":""},
    {"name":"Bisky Krueger","element":"Light","hairColor":"Pink/Blonde","type":"Human","hp":"67","atk":"96","def":"62","spd":"95","talents":"","notes":""},
    {"name":"Blair","element":"Dark","hairColor":"Purple","type":"Non-Human","hp":"102","atk":"69","def":"68","spd":"84","talents":"","notes":""},
    {"name":"Blake Belladonna","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"80","atk":"96","def":"80","spd":"81","talents":"","notes":""},
    {"name":"Blood Red Commander Igris","element":"Neutral","hairColor":"None","type":"Non-Human","hp":"90","atk":"81","def":"84","spd":"85","talents":"","notes":""},
    {"name":"Bond Forger","element":"Neutral","hairColor":"White (Fur)","type":"Non-Human","hp":"83","atk":"89","def":"80","spd":"87","talents":"","notes":""},
    {"name":"Botan","element":"Light","hairColor":"Blue","type":"Non-Human","hp":"92","atk":"73","def":"81","spd":"81","talents":"","notes":""},
    {"name":"Braz D Blood","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"70","atk":"92","def":"87","spd":"75","talents":"","notes":""},
    {"name":"Brook","element":"Dark","hairColor":"Black Afro","type":"Non-Human","hp":"78","atk":"94","def":"72","spd":"79","talents":"","notes":""},
    {"name":"Brunhilde","element":"Neutral","hairColor":"White/Silver","type":"Non-Human","hp":"90","atk":"87","def":"78","spd":"72","talents":"","notes":""},
    {"name":"Buddha","element":"Light","hairColor":"Blonde","type":"Non-Human","hp":"80","atk":"74","def":"91","spd":"81","talents":"","notes":""},
    {"name":"Byakuya Togami","element":"Light","hairColor":"Blonde","type":"Human","hp":"89","atk":"70","def":"91","spd":"75","talents":"","notes":""},
    {"name":"Canute","element":"Water","hairColor":"Blonde","type":"Human","hp":"76","atk":"94","def":"80","spd":"89","talents":"","notes":""},
    {"name":"C.C.","element":"Light","hairColor":"Green","type":"Human","hp":"95","atk":"67","def":"93","spd":"70","talents":"","notes":"?"},
    {"name":"Celestia Ludenberg","element":"Dark","hairColor":"Black","type":"Human","hp":"91","atk":"70","def":"78","spd":"89","talents":"","notes":""},
    {"name":"Celty Sturluson","element":"Dark","hairColor":"None (Headless)","type":"Non-Human","hp":"103","atk":"82","def":"78","spd":"74","talents":"","notes":""},
    {"name":"Chainsaw Man","element":"Dark","hairColor":"Orange/Blonde","type":"Non-Human","hp":"69","atk":"102","def":"86","spd":"69","talents":"","notes":""},
    {"name":"Charmy Pappitson","element":"Dark","hairColor":"White/Silver","type":"Non-Human","hp":"82","atk":"87","def":"79","spd":"77","talents":"","notes":""},
    {"name":"Chifuyu Matsuno","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"86","atk":"75","def":"93","spd":"73","talents":"","notes":""},
    {"name":"Chihiro Ogino","element":"Light","hairColor":"Brown","type":"Human","hp":"100","atk":"70","def":"100","spd":"70","talents":"","notes":""},
    {"name":"Chika Fujiwara","element":"Light","hairColor":"Pink","type":"Human","hp":"87","atk":"90","def":"82","spd":"66","talents":"","notes":""},
    {"name":"Child Emperor","element":"Neutral","hairColor":"Brown","type":"Human","hp":"84","atk":"85","def":"62","spd":"93","talents":"","notes":""},
    {"name":"Chino Kafuu","element":"Water","hairColor":"Blue","type":"Human","hp":"80","atk":"95","def":"81","spd":"70","talents":"","notes":""},
    {"name":"Chisato Hasegawa","element":"Neutral","hairColor":"Brown","type":"Human","hp":"98","atk":"92","def":"64","spd":"70","talents":"","notes":"?"},
    {"name":"Chiya Ujimatsu","element":"Water","hairColor":"Purple","type":"Human","hp":"76","atk":"69","def":"98","spd":"77","talents":"","notes":""},
    {"name":"Chlammy Zell","element":"Neutral","hairColor":"White/Silver","type":"Human","hp":"81","atk":"81","def":"81","spd":"81","talents":"","notes":""},
    {"name":"Choji Tomiyama","element":"Dark","hairColor":"","type":"","hp":"84","atk":"94","def":"85","spd":"77","talents":"","notes":"?"},
    {"name":"Chomusuke","element":"Dark","hairColor":"Black (Fur)","type":"Non-Human","hp":"81","atk":"81","def":"81","spd":"81","talents":"","notes":""},
    {"name":"Choso","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"85","atk":"80","def":"91","spd":"65","talents":"","notes":""},
    {"name":"Chuuya Nakahara","element":"Dark","hairColor":"Orange/Red","type":"Human","hp":"70","atk":"89","def":"82","spd":"89","talents":"","notes":""},
    {"name":"Cid Kagenou","element":"Dark","hairColor":"Black","type":"Human","hp":"82","atk":"85","def":"82","spd":"86","talents":"","notes":""},
    {"name":"Cirno","element":"Water","hairColor":"Blue","type":"Non-Human","hp":"73","atk":"99","def":"73","spd":"90","talents":"","notes":""},
    {"name":"Cornelia Britannia","element":"Neutral","hairColor":"Purple","type":"Human","hp":"76","atk":"97","def":"74","spd":"73","talents":"","notes":""},
    {"name":"Cow Girl","element":"Water","hairColor":"Brown","type":"Human","hp":"98","atk":"74","def":"72","spd":"80","talents":"","notes":""},
    {"name":"Crona","element":"Dark","hairColor":"Pink","type":"Human","hp":"96","atk":"87","def":"62","spd":"79","talents":"","notes":""},
    {"name":"Crusch Karsten","element":"Neutral","hairColor":"Green","type":"Human","hp":"84","atk":"80","def":"78","spd":"85","talents":"","notes":""},
    {"name":"Cupid","element":"Light","hairColor":"Pink","type":"Non-Human","hp":"90","atk":"81","def":"81","spd":"90","talents":"","notes":""},
    {"name":"Daida","element":"Water","hairColor":"Black","type":"Human","hp":"82","atk":"80","def":"82","spd":"85","talents":"","notes":""},
    {"name":"Darkness","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"97","atk":"70","def":"91","spd":"61","talents":"","notes":""},
    {"name":"David Martinez","element":"Dark","hairColor":"Black","type":"Human","hp":"75","atk":"93","def":"70","spd":"95","talents":"","notes":""},
    {"name":"Deathrattle","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"74","atk":"86","def":"70","spd":"100","talents":"","notes":""},
    {"name":"Death The Kid","element":"Dark","hairColor":"Black/White","type":"Human","hp":"93","atk":"67","def":"75","spd":"88","talents":"","notes":""},
    {"name":"Delmon Gates","element":"Water","hairColor":"Brown","type":"Human","hp":"85","atk":"86","def":"98","spd":"70","talents":"","notes":""},
    {"name":"Delta","element":"Dark","hairColor":"Blonde","type":"Human","hp":"94","atk":"91","def":"78","spd":"77","talents":"","notes":""},
    {"name":"Denji","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"84","atk":"88","def":"91","spd":"70","talents":"","notes":""},
    {"name":"Desha","element":"Light","hairColor":"Purple","type":"Non-Human","hp":"84","atk":"95","def":"78","spd":"78","talents":"","notes":""},
    {"name":"Diablo","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"85","atk":"60","def":"77","spd":"100","talents":"","notes":""},
    {"name":"Doc","element":"Dark","hairColor":"Brown","type":"Human","hp":"81","atk":"92","def":"84","spd":"75","talents":"","notes":""},
    {"name":"Doppo Orochi","element":"Neutral","hairColor":"Black","type":"Human","hp":"75","atk":"90","def":"82","spd":"85","talents":"","notes":""},
    {"name":"Doraemon","element":"Light","hairColor":"None","type":"Non-Human","hp":"75","atk":"75","def":"90","spd":"90","talents":"","notes":""},
    {"name":"Dragon Boy","element":"Dark","hairColor":"Black","type":"Human","hp":"89","atk":"81","def":"91","spd":"82","talents":"","notes":""},
    {"name":"Dunn Smith","element":"Dark","hairColor":"Brown","type":"Human","hp":"79","atk":"87","def":"82","spd":"92","talents":"","notes":""},
    {"name":"Echidna","element":"Dark","hairColor":"White","type":"Non-Human","hp":"76","atk":"99","def":"84","spd":"67","talents":"","notes":""},
    {"name":"Eevee","element":"Neutral","hairColor":"Brown","type":"Non-Human","hp":"85","atk":"85","def":"85","spd":"85","talents":"","notes":""},
    {"name":"Einar","element":"Light","hairColor":"Brown","type":"Human","hp":"79","atk":"88","def":"82","spd":"85","talents":"","notes":""},
    {"name":"Elma","element":"Water","hairColor":"Pink/Orange","type":"Non-Human","hp":"86","atk":"85","def":"86","spd":"68","talents":"","notes":""},
    {"name":"Emilia","element":"Water","hairColor":"Silver/White","type":"Human","hp":"82","atk":"90","def":"72","spd":"76","talents":"","notes":""},
    {"name":"Endorsi Zahard","element":"Light","hairColor":"Pink","type":"Human","hp":"77","atk":"91","def":"75","spd":"88","talents":"","notes":""},
    {"name":"Envy","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"85","atk":"73","def":"76","spd":"88","talents":"","notes":""},
    {"name":"Epsilon (Eis)","element":"Light","hairColor":"Purple","type":"Human","hp":"103","atk":"70","def":"103","spd":"79","talents":"","notes":""},
    {"name":"Ereshkigal","element":"Light","hairColor":"Blonde","type":"Non-Human","hp":"92","atk":"70","def":"94","spd":"80","talents":"","notes":""},
    {"name":"Eri","element":"Light","hairColor":"White/Silver","type":"Human","hp":"79","atk":"84","def":"75","spd":"83","talents":"","notes":""},
    {"name":"Erina Nakiri","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"84","atk":"90","def":"76","spd":"76","talents":"","notes":""},
    {"name":"Eris","element":"Light","hairColor":"Blue","type":"Non-Human","hp":"82","atk":"84","def":"83","spd":"76","talents":"","notes":""},
    {"name":"Eru Chitanda","element":"Neutral","hairColor":"Black","type":"Human","hp":"80","atk":"84","def":"81","spd":"92","talents":"","notes":""},
    {"name":"Eruka Frog","element":"Light","hairColor":"Blonde","type":"Non-Human","hp":"74","atk":"78","def":"83","spd":"89","talents":"","notes":""},
    {"name":"Esdeath","element":"Water","hairColor":"Blue","type":"Human","hp":"70","atk":"97","def":"62","spd":"90","talents":"","notes":""},
    {"name":"Esil Radiru","element":"Dark","hairColor":"Red","type":"Non-Human","hp":"86","atk":"70","def":"87","spd":"95","talents":"","notes":""},
    {"name":"Eta","element":"Dark","hairColor":"Purple","type":"Human","hp":"84","atk":"85","def":"86","spd":"84","talents":"","notes":""},
    {"name":"Eto Yoshimura","element":"Dark","hairColor":"Green","type":"Non-Human","hp":"95","atk":"80","def":"78","spd":"73","talents":"","notes":""},
    {"name":"Eugeo","element":"Water","hairColor":"Blonde","type":"Human","hp":"73","atk":"89","def":"76","spd":"84","talents":"","notes":""},
    {"name":"Exusiai","element":"Light","hairColor":"Red/Orange","type":"Non-Human","hp":"85","atk":"92","def":"66","spd":"95","talents":"","notes":""},
    {"name":"Fafnir","element":"Dark","hairColor":"Silver","type":"Non-Human","hp":"89","atk":"83","def":"74","spd":"79","talents":"","notes":""},
    {"name":"Faraday","element":"Dark","hairColor":"Black","type":"Human","hp":"85","atk":"85","def":"80","spd":"80","talents":"","notes":""},
    {"name":"Faris Nyannyan","element":"Water","hairColor":"Pink","type":"Human","hp":"75","atk":"80","def":"85","spd":"85","talents":"","notes":""},
    {"name":"Faye Valentine","element":"Light","hairColor":"Purple","type":"Human","hp":"85","atk":"91","def":"74","spd":"77","talents":"","notes":""},
    {"name":"Felix Argyle","element":"Neutral","hairColor":"Brown","type":"Human","hp":"102","atk":"73","def":"77","spd":"68","talents":"","notes":""},
    {"name":"Ferid Bathory","element":"Dark","hairColor":"Silver","type":"Non-Human","hp":"70","atk":"92","def":"86","spd":"70","talents":"","notes":""},
    {"name":"Fern","element":"Light","hairColor":"Purple","type":"Human","hp":"80","atk":"93","def":"70","spd":"88","talents":"","notes":""},
    {"name":"Fiel Nirvalen (Fii)","element":"Light","hairColor":"Purple","type":"Non-Human","hp":"73","atk":"86","def":"86","spd":"79","talents":"","notes":""},
    {"name":"Filo","element":"Light","hairColor":"Blonde","type":"Non-Human","hp":"85","atk":"76","def":"83","spd":"79","talents":"","notes":""},
    {"name":"Finn Ames","element":"Light","hairColor":"Black","type":"Human","hp":"75","atk":"90","def":"82","spd":"88","talents":"","notes":""},
    {"name":"Fiona Frost","element":"Water","hairColor":"Silver","type":"Human","hp":"86","atk":"75","def":"78","spd":"84","talents":"","notes":""},
    {"name":"First Hassan","element":"Dark","hairColor":"None","type":"Human","hp":"78","atk":"92","def":"74","spd":"90","talents":"","notes":""},
    {"name":"Fitoria","element":"Light","hairColor":"White","type":"Non-Human","hp":"90","atk":"82","def":"76","spd":"77","talents":"","notes":""},
    {"name":"Flashy Flash","element":"Light","hairColor":"Blonde","type":"Human","hp":"84","atk":"70","def":"77","spd":"100","talents":"","notes":""},
    {"name":"Franken Stein","element":"Dark","hairColor":"Gray","type":"Human","hp":"93","atk":"81","def":"85","spd":"67","talents":"","notes":""},
    {"name":"Frederica","element":"Light","hairColor":"Green","type":"Non-Human","hp":"91","atk":"70","def":"87","spd":"79","talents":"","notes":""},
    {"name":"Frieza","element":"Neutral","hairColor":"None","type":"Non-Human","hp":"85","atk":"90","def":"75","spd":"80","talents":"","notes":""},
    {"name":"Fumikage Tokoyami","element":"Dark","hairColor":"Black","type":"Human","hp":"86","atk":"71","def":"67","spd":"95","talents":"","notes":""},
    {"name":"Fuutarou Uesugi","element":"Neutral","hairColor":"Black","type":"Human","hp":"80","atk":"80","def":"80","spd":"80","talents":"","notes":""},
    {"name":"Fuyumi Yanagi","element":"Water","hairColor":"Black","type":"Non-Human","hp":"79","atk":"88","def":"84","spd":"75","talents":"","notes":""},
    {"name":"Garou","element":"Neutral","hairColor":"White/Silver","type":"Human","hp":"70","atk":"82","def":"91","spd":"80","talents":"","notes":""},
    {"name":"Gen Asagiri","element":"Neutral","hairColor":"Black","type":"Human","hp":"96","atk":"60","def":"84","spd":"82","talents":"","notes":""},
    {"name":"Gesicht","element":"Dark","hairColor":"None","type":"Non-Human","hp":"90","atk":"62","def":"98","spd":"90","talents":"","notes":""},
    {"name":"Ghost","element":"Dark","hairColor":"White","type":"Non-Human","hp":"75","atk":"75","def":"75","spd":"75","talents":"","notes":""},
    {"name":"Ghostblade","element":"Dark","hairColor":"White","type":"Human","hp":"79","atk":"97","def":"70","spd":"94","talents":"","notes":""},
    {"name":"Gilbert Bougainvillea","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"81","atk":"96","def":"81","spd":"70","talents":"","notes":""},
    {"name":"Giyu Tomioka","element":"Water","hairColor":"Black","type":"Human","hp":"76","atk":"80","def":"81","spd":"93","talents":"","notes":""},
    {"name":"Glacial Reindeer","element":"Water","hairColor":"White/Brown","type":"Non-Human","hp":"79","atk":"100","def":"86","spd":"74","talents":"","notes":""},
    {"name":"Gon Freecss","element":"Light","hairColor":"Black","type":"Human","hp":"80","atk":"86","def":"80","spd":"77","talents":"","notes":""},
    {"name":"Goto Ryuji","element":"Dark","hairColor":"Black","type":"Human","hp":"84","atk":"85","def":"74","spd":"86","talents":"","notes":""},
    {"name":"Gouki Shibukawa","element":"Light","hairColor":"White","type":"Human","hp":"84","atk":"89","def":"83","spd":"77","talents":"","notes":""},
    {"name":"Gowther","element":"Water","hairColor":"Pink/Orange","type":"Non-Human","hp":"89","atk":"63","def":"82","spd":"83","talents":"","notes":""},
    {"name":"Gravemonger","element":"Dark","hairColor":"None","type":"Non-Human","hp":"95","atk":"97","def":"79","spd":"70","talents":"","notes":""},
    {"name":"Gray Fullbuster","element":"Water","hairColor":"Black","type":"Human","hp":"81","atk":"83","def":"80","spd":"79","talents":"","notes":""},
    {"name":"Greed","element":"Neutral","hairColor":"Black","type":"Non-Human","hp":"84","atk":"73","def":"95","spd":"72","talents":"","notes":""},
    {"name":"Griffith","element":"Dark","hairColor":"White","type":"Human","hp":"85","atk":"100","def":"60","spd":"90","talents":"","notes":""},
    {"name":"Grimmjow Jeagerjaques","element":"Dark","hairColor":"Blue","type":"Non-Human","hp":"67","atk":"94","def":"68","spd":"95","talents":"","notes":""},
    {"name":"Gris Rubion","element":"Neutral","hairColor":"White","type":"Human","hp":"100","atk":"67","def":"100","spd":"67","talents":"","notes":""},
    {"name":"Guren Ichinose","element":"Neutral","hairColor":"Purple","type":"Human","hp":"63","atk":"85","def":"95","spd":"80","talents":"","notes":""},
    {"name":"Guts","element":"Neutral","hairColor":"Black","type":"Human","hp":"100","atk":"85","def":"88","spd":"63","talents":"","notes":""},
    {"name":"Hajime Kokonoi","element":"Dark","hairColor":"Black","type":"Human","hp":"81","atk":"86","def":"72","spd":"95","talents":"","notes":""},
    {"name":"Hajime Nagumo","element":"Light","hairColor":"White","type":"Human","hp":"91","atk":"82","def":"74","spd":"81","talents":"","notes":""},
    {"name":"Hakase Shinonome","element":"Light","hairColor":"Brown","type":"Human","hp":"82","atk":"80","def":"86","spd":"86","talents":"","notes":""},
    {"name":"Haku","element":"Water","hairColor":"Black","type":"Non-Human","hp":"89","atk":"95","def":"81","spd":"75","talents":"","notes":""},
    {"name":"Hange Zoe","element":"Light","hairColor":"Brown","type":"Human","hp":"85","atk":"76","def":"78","spd":"90","talents":"","notes":""},
    {"name":"Happy","element":"Water","hairColor":"Blue","type":"Non-Human","hp":"84","atk":"83","def":"71","spd":"90","talents":"","notes":""},
    {"name":"Hatsune Miku","element":"Water","hairColor":"Teal/Blue","type":"Non-Human","hp":"85","atk":"78","def":"83","spd":"83","talents":"","notes":""},
    {"name":"Hayase Nagatoro","element":"Neutral","hairColor":"Black","type":"Human","hp":"83","atk":"87","def":"64","spd":"93","talents":"","notes":""},
    {"name":"Headmaster Gator","element":"Water","hairColor":"Green","type":"Non-Human","hp":"80","atk":"95","def":"85","spd":"74","talents":"","notes":""},
    {"name":"Hei","element":"Dark","hairColor":"Black","type":"Human","hp":"80","atk":"85","def":"80","spd":"81","talents":"","notes":""},
    {"name":"Hellhound Overlord","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"82","atk":"86","def":"74","spd":"92","talents":"","notes":""},
    {"name":"Herald Of Damnation","element":"Dark","hairColor":"None","type":"Non-Human","hp":"90","atk":"90","def":"90","spd":"90","talents":"","notes":""},
    {"name":"Herald Of Salvation","element":"Light","hairColor":"None","type":"Non-Human","hp":"90","atk":"90","def":"90","spd":"90","talents":"","notes":""},
    {"name":"Hestia","element":"Light","hairColor":"Black","type":"Non-Human","hp":"85","atk":"73","def":"83","spd":"87","talents":"","notes":""},
    {"name":"Hibino Kafka","element":"Dark","hairColor":"Black","type":"Human","hp":"80","atk":"95","def":"76","spd":"89","talents":"","notes":""},
    {"name":"Hideyoshi Kinoshita","element":"Neutral","hairColor":"Brown","type":"Human","hp":"96","atk":"70","def":"93","spd":"72","talents":"","notes":""},
    {"name":"Hiei","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"93","atk":"86","def":"82","spd":"58","talents":"","notes":""},
    {"name":"Hilling","element":"Light","hairColor":"Purple","type":"Human","hp":"96","atk":"84","def":"76","spd":"74","talents":"","notes":""},
    {"name":"Himiko Toga","element":"Dark","hairColor":"Blonde","type":"Human","hp":"79","atk":"85","def":"86","spd":"79","talents":"","notes":""},
    {"name":"Hinami Fueguchi","element":"Dark","hairColor":"Brown","type":"Non-Human","hp":"74","atk":"88","def":"81","spd":"77","talents":"","notes":""},
    {"name":"Hinata Hyuga","element":"Neutral","hairColor":"Black/Purple","type":"Human","hp":"85","atk":"75","def":"94","spd":"69","talents":"","notes":""},
    {"name":"Hiro (016)","element":"Neutral","hairColor":"Black","type":"Human","hp":"89","atk":"96","def":"60","spd":"77","talents":"","notes":""},
    {"name":"Hisako Arato","element":"Neutral","hairColor":"Pink","type":"Human","hp":"69","atk":"83","def":"85","spd":"90","talents":"","notes":""},
    {"name":"Hisoka Morrow","element":"Dark","hairColor":"Red/Pink","type":"Human","hp":"83","atk":"72","def":"90","spd":"75","talents":"","notes":""},
    {"name":"Historia Reiss","element":"Light","hairColor":"Blonde","type":"Human","hp":"83","atk":"77","def":"95","spd":"73","talents":"","notes":""},
    {"name":"Hiyori Iki","element":"Water","hairColor":"Brown","type":"Human","hp":"72","atk":"80","def":"93","spd":"81","talents":"","notes":""},
    {"name":"Hizuru Minakata","element":"Dark","hairColor":"Black","type":"Human","hp":"70","atk":"99","def":"99","spd":"70","talents":"","notes":""},
    {"name":"Homura Akemi","element":"Dark","hairColor":"Black","type":"Human","hp":"71","atk":"88","def":"84","spd":"84","talents":"","notes":""},
    {"name":"Honami Ichinose","element":"Light","hairColor":"Pink","type":"Human","hp":"70","atk":"90","def":"87","spd":"81","talents":"","notes":""},
    {"name":"Horohoro","element":"Water","hairColor":"Blue","type":"Human","hp":"90","atk":"75","def":"86","spd":"80","talents":"","notes":""},
    {"name":"Hotaru Takegawa","element":"Water","hairColor":"Black","type":"Human","hp":"83","atk":"89","def":"66","spd":"91","talents":"","notes":""},
    {"name":"Houka Inumuta","element":"Water","hairColor":"Black","type":"Human","hp":"90","atk":"86","def":"75","spd":"74","talents":"","notes":""},
    {"name":"Houtarou Oreki","element":"Neutral","hairColor":"Brown","type":"Human","hp":"74","atk":"91","def":"78","spd":"94","talents":"","notes":""},
    {"name":"Howl Jenkins Pendragon","element":"Light","hairColor":"Blonde","type":"Human","hp":"90","atk":"73","def":"95","spd":"65","talents":"","notes":""},
    {"name":"Hyoma Chigiri","element":"Water","hairColor":"Pink/Red","type":"Human","hp":"84","atk":"85","def":"71","spd":"99","talents":"","notes":""},
    {"name":"Ichigo (015)","element":"Water","hairColor":"Blue","type":"Human","hp":"81","atk":"65","def":"90","spd":"83","talents":"","notes":""},
    {"name":"Ichigo Kurosaki","element":"Dark","hairColor":"Orange","type":"Human","hp":"89","atk":"102","def":"64","spd":"66","talents":"","notes":""},
    {"name":"Ichiya","element":"Water","hairColor":"Brown","type":"Human","hp":"78","atk":"94","def":"83","spd":"82","talents":"","notes":""},
    {"name":"Illyasviel Von Einzbern","element":"Water","hairColor":"Silver/White","type":"Human","hp":"84","atk":"85","def":"78","spd":"76","talents":"","notes":""},
    {"name":"Inosuke Hashibira","element":"Dark","hairColor":"Black","type":"Human","hp":"90","atk":"88","def":"81","spd":"62","talents":"","notes":""},
    {"name":"Inuyasha","element":"Dark","hairColor":"White/Silver","type":"Non-Human","hp":"84","atk":"81","def":"68","spd":"92","talents":"","notes":""},
    {"name":"Irina Jelavic","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"84","atk":"76","def":"85","spd":"80","talents":"","notes":""},
    {"name":"Iris","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"88","atk":"70","def":"96","spd":"72","talents":"","notes":""},
    {"name":"Iroha Tamaki","element":"Light","hairColor":"Pink","type":"Human","hp":"81","atk":"76","def":"82","spd":"89","talents":"","notes":""},
    {"name":"Iron Maiden Jeanne","element":"Light","hairColor":"Blonde","type":"Human","hp":"80","atk":"85","def":"80","spd":"80","talents":"","notes":""},
    {"name":"Isabella","element":"Dark","hairColor":"Purple","type":"Human","hp":"78","atk":"96","def":"82","spd":"71","talents":"","notes":""},
    {"name":"Ishtar","element":"Light","hairColor":"Blonde","type":"Non-Human","hp":"91","atk":"92","def":"78","spd":"79","talents":"","notes":""},
    {"name":"Issei Hyoudou","element":"Dark","hairColor":"Brown","type":"Human","hp":"82","atk":"86","def":"70","spd":"86","talents":"","notes":""},
    {"name":"Itachi Uchiha","element":"Dark","hairColor":"Black","type":"Human","hp":"82","atk":"101","def":"70","spd":"72","talents":"","notes":""},
    {"name":"Iz","element":"Water","hairColor":"Purple","type":"Human","hp":"100","atk":"76","def":"80","spd":"62","talents":"","notes":""},
    {"name":"Izumi Kyoka","element":"Water","hairColor":"Black","type":"Human","hp":"85","atk":"80","def":"82","spd":"80","talents":"","notes":""},
    {"name":"Izumi Sakurai","element":"Neutral","hairColor":"Blue","type":"Human","hp":"82","atk":"87","def":"99","spd":"70","talents":"","notes":""},
    {"name":"Izumo Kamiki","element":"Dark","hairColor":"Purple","type":"Human","hp":"93","atk":"75","def":"82","spd":"76","talents":"","notes":""},
    {"name":"Jabber Wonger","element":"Dark","hairColor":"Black","type":"Human","hp":"95","atk":"99","def":"67","spd":"79","talents":"","notes":""},
    {"name":"Jack Frost","element":"Water","hairColor":"White","type":"Non-Human","hp":"82","atk":"110","def":"70","spd":"73","talents":"","notes":""},
    {"name":"Jack The Ripper","element":"Light","hairColor":"Blonde","type":"Human","hp":"80","atk":"81","def":"63","spd":"91","talents":"","notes":""},
    {"name":"James","element":"Water","hairColor":"Purple","type":"Human","hp":"74","atk":"99","def":"93","spd":"70","talents":"","notes":""},
    {"name":"Jellal Fernandes","element":"Dark","hairColor":"Blue","type":"Human","hp":"69","atk":"94","def":"98","spd":"64","talents":"","notes":""},
    {"name":"Jibril","element":"Light","hairColor":"Pink/White","type":"Non-Human","hp":"81","atk":"88","def":"75","spd":"80","talents":"","notes":""},
    {"name":"Jimihen","element":"Light","hairColor":"Black","type":"Human","hp":"99","atk":"60","def":"99","spd":"80","talents":"","notes":""},
    {"name":"Jinbei","element":"Water","hairColor":"Black","type":"Non-Human","hp":"83","atk":"86","def":"76","spd":"82","talents":"","notes":""},
    {"name":"Jinx","element":"Dark","hairColor":"Blue","type":"Human","hp":"78","atk":"87","def":"77","spd":"95","talents":"","notes":""},
    {"name":"Johnny Joestar","element":"Water","hairColor":"Blonde","type":"Human","hp":"95","atk":"95","def":"88","spd":"53","talents":"","notes":""},
    {"name":"Joker","element":"Light","hairColor":"Green","type":"Human","hp":"95","atk":"91","def":"70","spd":"80","talents":"","notes":""},
    {"name":"Jolyne Kujo","element":"Water","hairColor":"Green/Blue","type":"Human","hp":"81","atk":"89","def":"80","spd":"79","talents":"","notes":""},
    {"name":"Jonathan Joestar","element":"Light","hairColor":"Blue","type":"Human","hp":"84","atk":"90","def":"74","spd":"77","talents":"","notes":""},
    {"name":"Joseph Joestar","element":"Neutral","hairColor":"Brown","type":"Human","hp":"96","atk":"88","def":"72","spd":"70","talents":"","notes":""},
    {"name":"Jotaro Kujo","element":"Light","hairColor":"Black","type":"Human","hp":"80","atk":"90","def":"80","spd":"75","talents":"","notes":""},
    {"name":"Jo Togame","element":"Dark","hairColor":"Orange","type":"Human","hp":"84","atk":"86","def":"90","spd":"80","talents":"","notes":""},
    {"name":"Judar","element":"Neutral","hairColor":"Black","type":"Human","hp":"65","atk":"78","def":"91","spd":"86","talents":"","notes":""},
    {"name":"Julia","element":"Neutral","hairColor":"Purple","type":"Human","hp":"70","atk":"80","def":"90","spd":"80","talents":"","notes":""},
    {"name":"July","element":"Light","hairColor":"Silver","type":"Non-Human","hp":"78","atk":"75","def":"97","spd":"70","talents":"","notes":""},
    {"name":"Junpei Hyuga","element":"Water","hairColor":"Black","type":"Human","hp":"90","atk":"80","def":"93","spd":"75","talents":"","notes":""},
    {"name":"Juvia Lockser","element":"Dark","hairColor":"Blue","type":"Human","hp":"75","atk":"97","def":"80","spd":"71","talents":"","notes":""},
    {"name":"Kage","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"83","atk":"85","def":"72","spd":"96","talents":"","notes":""},
    {"name":"Kaguya Shinomiya","element":"Dark","hairColor":"Black","type":"Human","hp":"84","atk":"77","def":"88","spd":"76","talents":"","notes":""},
    {"name":"Kakeru Sengoku","element":"Light","hairColor":"Black","type":"Human","hp":"101","atk":"97","def":"60","spd":"75","talents":"","notes":""},
    {"name":"Kakine Teitoku","element":"Light","hairColor":"White/Silver","type":"Human","hp":"70","atk":"86","def":"86","spd":"84","talents":"","notes":""},
    {"name":"Kamijou Touma","element":"Light","hairColor":"Black","type":"Human","hp":"84","atk":"89","def":"71","spd":"77","talents":"","notes":""},
    {"name":"Kanade Tachibana","element":"Neutral","hairColor":"Silver/White","type":"Human","hp":"70","atk":"89","def":"75","spd":"87","talents":"","notes":""},
    {"name":"Kanao Tsuyuri","element":"Dark","hairColor":"Black","type":"Human","hp":"69","atk":"81","def":"96","spd":"77","talents":"","notes":""},
    {"name":"Kaneki Ken","element":"Dark","hairColor":"White","type":"Non-Human","hp":"73","atk":"99","def":"75","spd":"80","talents":"","notes":""},
    {"name":"Kang Taeshik","element":"Water","hairColor":"Brown","type":"Human","hp":"73","atk":"89","def":"78","spd":"100","talents":"","notes":""},
    {"name":"Kaori Shirasaki","element":"Water","hairColor":"Blonde","type":"Human","hp":"91","atk":"73","def":"94","spd":"68","talents":"","notes":""},
    {"name":"Kaoru Hanayama","element":"Water","hairColor":"Black","type":"Human","hp":"83","atk":"65","def":"96","spd":"82","talents":"","notes":""},
    {"name":"Kaworu Nagisa","element":"Neutral","hairColor":"Gray/Silver","type":"Non-Human","hp":"71","atk":"86","def":"91","spd":"83","talents":"","notes":""},
    {"name":"Kazuma Satou","element":"Water","hairColor":"Brown","type":"Human","hp":"75","atk":"84","def":"100","spd":"64","talents":"","notes":""},
    {"name":"Kei Karuizawa","element":"Water","hairColor":"Blonde","type":"Human","hp":"74","atk":"80","def":"85","spd":"88","talents":"","notes":""},
    {"name":"Kei Shirogane","element":"Dark","hairColor":"Black","type":"Human","hp":"88","atk":"76","def":"75","spd":"93","talents":"","notes":""},
    {"name":"Kei Tsukishima","element":"Light","hairColor":"Blonde","type":"Human","hp":"78","atk":"78","def":"93","spd":"76","talents":"","notes":""},
    {"name":"Kei Uzuki","element":"Water","hairColor":"Black","type":"Human","hp":"90","atk":"79","def":"94","spd":"80","talents":"","notes":""},
    {"name":"Kenma Kozume","element":"Dark","hairColor":"Blonde","type":"Human","hp":"90","atk":"87","def":"68","spd":"81","talents":"","notes":""},
    {"name":"Kid Buu","element":"Light","hairColor":"None","type":"Non-Human","hp":"80","atk":"83","def":"81","spd":"78","talents":"","notes":""},
    {"name":"Kikyo","element":"Light","hairColor":"Black","type":"Human","hp":"80","atk":"85","def":"74","spd":"80","talents":"","notes":""},
    {"name":"Kikyou Kushida","element":"Neutral","hairColor":"Brown","type":"Human","hp":"81","atk":"78","def":"83","spd":"86","talents":"","notes":""},
    {"name":"Kim Chul (Iron)","element":"Neutral","hairColor":"Brown","type":"Human","hp":"110","atk":"73","def":"82","spd":"70","talents":"","notes":""},
    {"name":"King","element":"Dark","hairColor":"Brown","type":"Human","hp":"91","atk":"79","def":"82","spd":"80","talents":"","notes":""},
    {"name":"Kingpin Grinch","element":"Light","hairColor":"Green","type":"Non-Human","hp":"92","atk":"83","def":"73","spd":"90","talents":"","notes":""},
    {"name":"Kirari Momobami","element":"Dark","hairColor":"White/Silver","type":"Human","hp":"85","atk":"84","def":"76","spd":"82","talents":"","notes":""},
    {"name":"Kirito","element":"Dark","hairColor":"Black","type":"Human","hp":"82","atk":"90","def":"73","spd":"85","talents":"","notes":""},
    {"name":"Kiritsugu Emiya","element":"Neutral","hairColor":"Black","type":"Human","hp":"70","atk":"85","def":"77","spd":"90","talents":"","notes":""},
    {"name":"Kishirika Kishirisu","element":"Dark","hairColor":"Pink","type":"Non-Human","hp":"100","atk":"100","def":"50","spd":"57","talents":"","notes":""},
    {"name":"Kishou Arima","element":"Dark","hairColor":"White","type":"Human","hp":"76","atk":"78","def":"79","spd":"94","talents":"","notes":""},
    {"name":"Kisuke Urahara","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"90","atk":"72","def":"84","spd":"85","talents":"","notes":""},
    {"name":"Kiyotaka Ayanokouji","element":"Neutral","hairColor":"Brown","type":"Human","hp":"80","atk":"80","def":"60","spd":"90","talents":"","notes":""},
    {"name":"Kobayashi","element":"Light","hairColor":"Orange/Red","type":"Human","hp":"86","atk":"75","def":"82","spd":"79","talents":"","notes":""},
    {"name":"Kokomi Teruhashi","element":"Neutral","hairColor":"Blue","type":"Human","hp":"84","atk":"88","def":"72","spd":"88","talents":"","notes":""},
    {"name":"Komi Shouko","element":"Neutral","hairColor":"Purple","type":"Human","hp":"80","atk":"88","def":"70","spd":"93","talents":"","notes":""},
    {"name":"Koneko Toujou","element":"Light","hairColor":"White","type":"Non-Human","hp":"89","atk":"72","def":"71","spd":"89","talents":"","notes":""},
    {"name":"Koro Sensei","element":"Neutral","hairColor":"None","type":"Non-Human","hp":"73","atk":"85","def":"73","spd":"100","talents":"","notes":""},
    {"name":"Kougyoku","element":"Water","hairColor":"Red","type":"Human","hp":"88","atk":"87","def":"73","spd":"76","talents":"","notes":""},
    {"name":"Kouta","element":"Dark","hairColor":"Black","type":"Human","hp":"72","atk":"87","def":"85","spd":"81","talents":"","notes":""},
    {"name":"Krampus","element":"Water","hairColor":"Brown","type":"Non-Human","hp":"95","atk":"70","def":"95","spd":"80","talents":"","notes":""},
    {"name":"Krillin","element":"Neutral","hairColor":"Bald","type":"Human","hp":"96","atk":"91","def":"68","spd":"65","talents":"","notes":""},
    {"name":"Krul Tepes","element":"Water","hairColor":"Pink","type":"Non-Human","hp":"65","atk":"74","def":"94","spd":"87","talents":"","notes":""},
    {"name":"Kuchiki Byakuya","element":"Neutral","hairColor":"Black","type":"Human","hp":"70","atk":"93","def":"91","spd":"70","talents":"","notes":""},
    {"name":"Kurapika","element":"Dark","hairColor":"Blonde","type":"Human","hp":"75","atk":"77","def":"85","spd":"87","talents":"","notes":""},
    {"name":"Kurome","element":"Light","hairColor":"Black","type":"Human","hp":"90","atk":"87","def":"72","spd":"80","talents":"","notes":""},
    {"name":"Kurumi Nonaka","element":"Water","hairColor":"Brown","type":"Human","hp":"75","atk":"97","def":"74","spd":"76","talents":"","notes":""},
    {"name":"Kusuo Saiki","element":"Water","hairColor":"Pink","type":"Human","hp":"81","atk":"75","def":"83","spd":"90","talents":"","notes":""},
    {"name":"Kyoko Kirigiri","element":"Light","hairColor":"Purple","type":"Human","hp":"68","atk":"87","def":"82","spd":"90","talents":"","notes":""},
    {"name":"Kyoraku Shunsui","element":"Light","hairColor":"Brown","type":"Human","hp":"86","atk":"89","def":"84","spd":"71","talents":"","notes":""},
    {"name":"Kyouko Hori","element":"Light","hairColor":"Brown","type":"Human","hp":"80","atk":"79","def":"96","spd":"82","talents":"","notes":""},
    {"name":"Kyoya Hibari","element":"Water","hairColor":"Black","type":"Human","hp":"73","atk":"79","def":"82","spd":"88","talents":"","notes":""},
    {"name":"Kyubey","element":"Water","hairColor":"White (Fur)","type":"Non-Human","hp":"97","atk":"60","def":"94","spd":"89","talents":"","notes":""},
    {"name":"L","element":"Water","hairColor":"Black","type":"Human","hp":"88","atk":"73","def":"80","spd":"87","talents":"","notes":""},
    {"name":"Lady Of Death","element":"Water","hairColor":"White","type":"Non-Human","hp":"74","atk":"85","def":"95","spd":"82","talents":"","notes":""},
    {"name":"Lee Joohee","element":"Dark","hairColor":"Red","type":"Human","hp":"81","atk":"80","def":"82","spd":"75","talents":"","notes":""},
    {"name":"Lelouch Lamperouge","element":"Water","hairColor":"Black","type":"Human","hp":"80","atk":"64","def":"86","spd":"90","talents":"","notes":""},
    {"name":"Lemon Irvine","element":"Dark","hairColor":"Yellow/Blonde","type":"Human","hp":"87","atk":"75","def":"90","spd":"82","talents":"","notes":""},
    {"name":"Leone","element":"Dark","hairColor":"Blonde","type":"Human","hp":"98","atk":"82","def":"78","spd":"75","talents":"","notes":""},
    {"name":"Leorio Paradinight","element":"Dark","hairColor":"Black","type":"Human","hp":"75","atk":"81","def":"79","spd":"92","talents":"","notes":""},
    {"name":"Lero Ro","element":"Water","hairColor":"Brown","type":"Human","hp":"79","atk":"95","def":"70","spd":"83","talents":"","notes":""},
    {"name":"Libram Spectre","element":"Dark","hairColor":"White","type":"Non-Human","hp":"101","atk":"70","def":"103","spd":"60","talents":"","notes":""},
    {"name":"Light Yagami (Kira)","element":"Dark","hairColor":"Brown","type":"Human","hp":"86","atk":"100","def":"78","spd":"61","talents":"","notes":""},
    {"name":"Lilith G.G.O","element":"Neutral","hairColor":"Brown","type":"Human","hp":"90","atk":"110","def":"90","spd":"95","talents":"","notes":""},
    {"name":"Lisa Lisa","element":"Dark","hairColor":"Black","type":"Human","hp":"83","atk":"89","def":"74","spd":"82","talents":"","notes":""},
    {"name":"Liz T Blood","element":"Neutral","hairColor":"Red","type":"Non-Human","hp":"78","atk":"87","def":"68","spd":"92","talents":"","notes":""},
    {"name":"Loid Forger (Twilight)","element":"Water","hairColor":"Blonde","type":"Human","hp":"70","atk":"98","def":"82","spd":"80","talents":"","notes":""},
    {"name":"Loli","element":"Neutral","hairColor":"Pink","type":"Human","hp":"91","atk":"63","def":"103","spd":"74","talents":"","notes":""},
    {"name":"Lucky Cyan","element":"Dark","hairColor":"Cyan","type":"Non-Human","hp":"90","atk":"90","def":"90","spd":"70","talents":"","notes":""},
    {"name":"Lucy Heartfilia","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"75","atk":"92","def":"86","spd":"68","talents":"","notes":""},
    {"name":"Lucy (Kaede)","element":"Water","hairColor":"Pink","type":"Non-Human","hp":"80","atk":"82","def":"90","spd":"80","talents":"","notes":""},
    {"name":"Lucy Kushinada","element":"Water","hairColor":"Black","type":"Human","hp":"78","atk":"81","def":"80","spd":"92","talents":"","notes":""},
    {"name":"Madara Uchiha","element":"Light","hairColor":"Black","type":"Human","hp":"88","atk":"90","def":"82","spd":"60","talents":"","notes":""},
    {"name":"Madoka Kaname","element":"Light","hairColor":"Pink","type":"Human","hp":"81","atk":"80","def":"93","spd":"73","talents":"","notes":""},
    {"name":"Mahoro Jin","element":"Light","hairColor":"Brown","type":"Human","hp":"94","atk":"70","def":"94","spd":"80","talents":"","notes":""},
    {"name":"Mai Minakami","element":"Water","hairColor":"Blue","type":"Human","hp":"97","atk":"72","def":"80","spd":"82","talents":"","notes":""},
    {"name":"Maine","element":"Light","hairColor":"White/Silver","type":"Human","hp":"78","atk":"84","def":"90","spd":"81","talents":"","notes":""},
    {"name":"Mai Sakurajima","element":"Water","hairColor":"Black","type":"Human","hp":"91","atk":"80","def":"86","spd":"70","talents":"","notes":""},
    {"name":"Majordoma","element":"Light","hairColor":"Gray","type":"Non-Human","hp":"100","atk":"85","def":"83","spd":"75","talents":"","notes":""},
    {"name":"Majordomo","element":"Dark","hairColor":"Gray","type":"Non-Human","hp":"80","atk":"80","def":"90","spd":"90","talents":"","notes":""},
    {"name":"Maka Albarn","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"87","atk":"80","def":"72","spd":"80","talents":"","notes":""},
    {"name":"Makima","element":"Light","hairColor":"Red/Orange","type":"Non-Human","hp":"84","atk":"92","def":"80","spd":"76","talents":"","notes":""},
    {"name":"Maki Zenin","element":"Water","hairColor":"Green","type":"Human","hp":"102","atk":"93","def":"74","spd":"70","talents":"","notes":""},
    {"name":"Makoto Naegi","element":"Neutral","hairColor":"Brown","type":"Human","hp":"81","atk":"81","def":"81","spd":"83","talents":"","notes":""},
    {"name":"Mami Tomoe","element":"Light","hairColor":"Blonde","type":"Human","hp":"61","atk":"90","def":"64","spd":"99","talents":"","notes":""},
    {"name":"Mamoru Chiba (Tuxedo Mask)","element":"Neutral","hairColor":"Black","type":"Human","hp":"82","atk":"87","def":"73","spd":"77","talents":"","notes":""},
    {"name":"Maomao","element":"Water","hairColor":"Black","type":"Human","hp":"90","atk":"90","def":"80","spd":"85","talents":"","notes":""},
    {"name":"Maple","element":"Dark","hairColor":"Brown","type":"Human","hp":"65","atk":"65","def":"130","spd":"65","talents":"","notes":""},
    {"name":"Maria Naruse","element":"Dark","hairColor":"Silver/White","type":"Non-Human","hp":"84","atk":"68","def":"93","spd":"80","talents":"","notes":""},
    {"name":"Marin Kitagawa","element":"Light","hairColor":"Blonde","type":"Human","hp":"102","atk":"65","def":"80","spd":"93","talents":"","notes":""},
    {"name":"Mary Saotome","element":"Water","hairColor":"Blonde","type":"Human","hp":"78","atk":"79","def":"86","spd":"84","talents":"","notes":""},
    {"name":"Masahito Karikiri","element":"Dark","hairColor":"Black","type":"Human","hp":"70","atk":"80","def":"90","spd":"100","talents":"","notes":""},
    {"name":"Mash Burnedead","element":"Light","hairColor":"Black","type":"Human","hp":"95","atk":"95","def":"95","spd":"90","talents":"","notes":""},
    {"name":"Mash Kyrielight","element":"Water","hairColor":"Purple","type":"Human","hp":"81","atk":"81","def":"99","spd":"69","talents":"","notes":""},
    {"name":"Mavis Vermillion","element":"Neutral","hairColor":"Blonde","type":"Non-Human","hp":"63","atk":"87","def":"87","spd":"87","talents":"","notes":""},
    {"name":"Maya Joga","element":"Dark","hairColor":"Black","type":"Human","hp":"78","atk":"87","def":"93","spd":"65","talents":"","notes":""},
    {"name":"Mayu","element":"Dark","hairColor":"Pink","type":"Non-Human","hp":"90","atk":"82","def":"85","spd":"73","talents":"","notes":""},
    {"name":"Mayuri Shiina","element":"Light","hairColor":"Brown","type":"Human","hp":"66","atk":"66","def":"95","spd":"94","talents":"","notes":""},
    {"name":"Medusa Gorgon","element":"Dark","hairColor":"Blonde","type":"Non-Human","hp":"68","atk":"99","def":"65","spd":"90","talents":"","notes":""},
    {"name":"Megose","element":"Neutral","hairColor":"Black","type":"Human","hp":"88","atk":"86","def":"89","spd":"77","talents":"","notes":""},
    {"name":"Megumi Fushiguro","element":"Dark","hairColor":"Black","type":"Human","hp":"86","atk":"71","def":"92","spd":"78","talents":"","notes":""},
    {"name":"Megumi Natsu","element":"Neutral","hairColor":"Brown","type":"Human","hp":"85","atk":"91","def":"78","spd":"70","talents":"","notes":""},
    {"name":"Megumi Tadokoro","element":"Neutral","hairColor":"Blue","type":"Human","hp":"74","atk":"88","def":"92","spd":"70","talents":"","notes":""},
    {"name":"Meguru Bachira","element":"Neutral","hairColor":"Yellow/Blonde","type":"Human","hp":"90","atk":"75","def":"81","spd":"88","talents":"","notes":""},
    {"name":"Meiru Melusine","element":"Neutral","hairColor":"Blonde","type":"Non-Human","hp":"86","atk":"89","def":"84","spd":"71","talents":"","notes":""},
    {"name":"Melissa Moretti","element":"Water","hairColor":"Brown","type":"Human","hp":"90","atk":"80","def":"80","spd":"85","talents":"","notes":""},
    {"name":"Melt Narushima","element":"Light","hairColor":"Brown","type":"Human","hp":"87","atk":"80","def":"85","spd":"79","talents":"","notes":""},
    {"name":"Melty Q Melromarc","element":"Neutral","hairColor":"Blue","type":"Human","hp":"73","atk":"75","def":"87","spd":"86","talents":"","notes":""},
    {"name":"Mephisto Pheles","element":"Neutral","hairColor":"Purple","type":"Non-Human","hp":"70","atk":"100","def":"87","spd":"64","talents":"","notes":""},
    {"name":"Merlin","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"76","atk":"88","def":"89","spd":"71","talents":"","notes":""},
    {"name":"Mewtwo","element":"Dark","hairColor":"None","type":"Non-Human","hp":"84","atk":"96","def":"78","spd":"80","talents":"","notes":""},
    {"name":"Mikado Ryugamine","element":"Light","hairColor":"Black","type":"Human","hp":"86","atk":"83","def":"89","spd":"82","talents":"","notes":""},
    {"name":"Mikey","element":"Light","hairColor":"Blonde","type":"Human","hp":"85","atk":"81","def":"75","spd":"88","talents":"","notes":""},
    {"name":"Mikihiko Yoshida","element":"Light","hairColor":"Brown","type":"Human","hp":"95","atk":"80","def":"95","spd":"65","talents":"","notes":""},
    {"name":"Miku (390)","element":"Water","hairColor":"Blue","type":"Human","hp":"93","atk":"87","def":"74","spd":"71","talents":"","notes":""},
    {"name":"Mina Ashiro","element":"Water","hairColor":"Purple","type":"Human","hp":"82","atk":"92","def":"88","spd":"78","talents":"","notes":""},
    {"name":"Minako Aino (Sailor Venus)","element":"Water","hairColor":"Blonde","type":"Human","hp":"66","atk":"80","def":"94","spd":"87","talents":"","notes":""},
    {"name":"Minami Kotobuki","element":"Water","hairColor":"Blonde","type":"Human","hp":"75","atk":"102","def":"70","spd":"90","talents":"","notes":""},
    {"name":"Mine","element":"Dark","hairColor":"Pink","type":"Human","hp":"97","atk":"68","def":"94","spd":"66","talents":"","notes":""},
    {"name":"Minene Uryuu","element":"Water","hairColor":"Purple","type":"Human","hp":"87","atk":"90","def":"83","spd":"62","talents":"","notes":""},
    {"name":"Mio Akiyama","element":"Dark","hairColor":"Black","type":"Human","hp":"84","atk":"87","def":"78","spd":"71","talents":"","notes":""},
    {"name":"Mio Kofune","element":"Dark","hairColor":"Black","type":"Human","hp":"90","atk":"99","def":"75","spd":"70","talents":"","notes":""},
    {"name":"Mio Naganohara","element":"Dark","hairColor":"Brown","type":"Human","hp":"91","atk":"63","def":"95","spd":"88","talents":"","notes":""},
    {"name":"Mio Takamiya","element":"Water","hairColor":"Black","type":"Human","hp":"74","atk":"80","def":"72","spd":"99","talents":"","notes":""},
    {"name":"Misa Amane","element":"Dark","hairColor":"Blonde","type":"Human","hp":"85","atk":"97","def":"74","spd":"72","talents":"","notes":""},
    {"name":"Misery","element":"Dark","hairColor":"White","type":"Non-Human","hp":"79","atk":"94","def":"72","spd":"90","talents":"","notes":""},
    {"name":"Misty","element":"Neutral","hairColor":"Orange/Red","type":"Human","hp":"86","atk":"72","def":"90","spd":"83","talents":"","notes":""},
    {"name":"Mitsuri Kanroji","element":"Dark","hairColor":"Pink/Green","type":"Human","hp":"81","atk":"94","def":"72","spd":"88","talents":"","notes":""},
    {"name":"Miyuki Shiba","element":"Neutral","hairColor":"Black","type":"Human","hp":"94","atk":"74","def":"87","spd":"77","talents":"","notes":""},
    {"name":"Miyuki Shirogane","element":"Water","hairColor":"Black","type":"Human","hp":"84","atk":"83","def":"90","spd":"69","talents":"","notes":""},
    {"name":"Mizuki Shibata","element":"Neutral","hairColor":"Brown","type":"Human","hp":"90","atk":"82","def":"90","spd":"70","talents":"","notes":""},
    {"name":"Momo Ayase","element":"Dark","hairColor":"Brown","type":"Human","hp":"90","atk":"102","def":"75","spd":"70","talents":"","notes":""},
    {"name":"Monika","element":"Neutral","hairColor":"Brown","type":"Human","hp":"72","atk":"88","def":"75","spd":"93","talents":"","notes":""},
    {"name":"Monkey D Luffy","element":"Water","hairColor":"Black","type":"Human","hp":"70","atk":"90","def":"86","spd":"76","talents":"","notes":""},
    {"name":"Mukuro Rokudo","element":"Water","hairColor":"Blue","type":"Human","hp":"85","atk":"65","def":"91","spd":"79","talents":"","notes":""},
    {"name":"Muzan Kibutsuji","element":"Light","hairColor":"Black","type":"Non-Human","hp":"95","atk":"75","def":"80","spd":"75","talents":"","notes":""},
    {"name":"Myu","element":"Light","hairColor":"Blonde","type":"Non-Human","hp":"96","atk":"85","def":"83","spd":"68","talents":"","notes":""},
    {"name":"Nagisa Shiota","element":"Light","hairColor":"Blue","type":"Human","hp":"81","atk":"93","def":"74","spd":"80","talents":"","notes":""},
    {"name":"Nagi Seishiro","element":"Water","hairColor":"White","type":"Human","hp":"85","atk":"93","def":"68","spd":"86","talents":"","notes":""},
    {"name":"Nagito Komaeda","element":"Light","hairColor":"White","type":"Human","hp":"74","atk":"88","def":"89","spd":"72","talents":"","notes":""},
    {"name":"Naomi Misora","element":"Water","hairColor":"Black","type":"Human","hp":"67","atk":"88","def":"90","spd":"81","talents":"","notes":""},
    {"name":"Naraku","element":"Light","hairColor":"Black","type":"Non-Human","hp":"83","atk":"62","def":"96","spd":"79","talents":"","notes":""},
    {"name":"Natsuki","element":"Dark","hairColor":"Pink","type":"Human","hp":"95","atk":"78","def":"77","spd":"74","talents":"","notes":""},
    {"name":"Near","element":"Light","hairColor":"White","type":"Human","hp":"75","atk":"81","def":"62","spd":"88","talents":"","notes":""},
    {"name":"Nero","element":"Light","hairColor":"Black","type":"Human","hp":"75","atk":"84","def":"89","spd":"75","talents":"","notes":""},
    {"name":"Nezuko Kamado","element":"Neutral","hairColor":"Black","type":"Non-Human","hp":"84","atk":"82","def":"80","spd":"78","talents":"","notes":""},
    {"name":"Nianbeast","element":"Dark","hairColor":"None","type":"Non-Human","hp":"100","atk":"85","def":"100","spd":"55","talents":"","notes":""},
    {"name":"Nico Robin","element":"Dark","hairColor":"Black","type":"Human","hp":"90","atk":"90","def":"70","spd":"70","talents":"","notes":""},
    {"name":"Nino Nakano","element":"Water","hairColor":"Pink/Red","type":"Human","hp":"76","atk":"95","def":"76","spd":"76","talents":"","notes":""},
    {"name":"Nobuchika Ginoza","element":"Water","hairColor":"Black","type":"Human","hp":"95","atk":"66","def":"78","spd":"85","talents":"","notes":""},
    {"name":"Noelle Silva","element":"Dark","hairColor":"Pink","type":"Human","hp":"75","atk":"81","def":"93","spd":"77","talents":"","notes":""},
    {"name":"No Face","element":"Water","hairColor":"None","type":"Non-Human","hp":"83","atk":"91","def":"80","spd":"74","talents":"","notes":""},
    {"name":"Norman","element":"Water","hairColor":"White","type":"Human","hp":"76","atk":"93","def":"62","spd":"95","talents":"","notes":""},
    {"name":"November","element":"Dark","hairColor":"Silver","type":"Non-Human","hp":"87","atk":"82","def":"81","spd":"75","talents":"","notes":""},
    {"name":"Nurugai","element":"Dark","hairColor":"Black","type":"Human","hp":"68","atk":"91","def":"72","spd":"103","talents":"","notes":""},
    {"name":"Obanai Iguro","element":"Light","hairColor":"Black","type":"Human","hp":"77","atk":"90","def":"85","spd":"75","talents":"","notes":""},
    {"name":"Ochaco Uraraka","element":"Dark","hairColor":"Brown","type":"Human","hp":"92","atk":"97","def":"63","spd":"70","talents":"","notes":""},
    {"name":"Okita Sougo","element":"Light","hairColor":"Brown","type":"Human","hp":"81","atk":"93","def":"74","spd":"78","talents":"","notes":""},
    {"name":"Origami Tobiichi","element":"Dark","hairColor":"White","type":"Human","hp":"94","atk":"76","def":"79","spd":"73","talents":"","notes":""},
    {"name":"Osamu Dazai","element":"Light","hairColor":"Brown","type":"Human","hp":"80","atk":"88","def":"76","spd":"84","talents":"","notes":""},
    {"name":"Osaragi","element":"Water","hairColor":"Black","type":"Human","hp":"88","atk":"83","def":"87","spd":"81","talents":"","notes":""},
    {"name":"Ouken","element":"Neutral","hairColor":"White","type":"Non-Human","hp":"95","atk":"85","def":"82","spd":"73","talents":"","notes":""},
    {"name":"Padoru","element":"Dark","hairColor":"Blonde","type":"Human","hp":"90","atk":"95","def":"70","spd":"80","talents":"","notes":""},
    {"name":"Pain","element":"Dark","hairColor":"Orange","type":"Human","hp":"80","atk":"86","def":"85","spd":"78","talents":"","notes":""},
    {"name":"Pandoras Actor","element":"Dark","hairColor":"Orange/Blonde","type":"Non-Human","hp":"87","atk":"80","def":"89","spd":"80","talents":"","notes":""},
    {"name":"Payne","element":"Dark","hairColor":"Brown","type":"Human","hp":"80","atk":"84","def":"85","spd":"77","talents":"","notes":""},
    {"name":"Pennywise","element":"Light","hairColor":"Red/Orange","type":"Non-Human","hp":"102","atk":"80","def":"93","spd":"60","talents":"","notes":""},
    {"name":"Petelgeuse Romanee Conti","element":"Neutral","hairColor":"Black","type":"Human","hp":"88","atk":"91","def":"80","spd":"79","talents":"","notes":""},
    {"name":"Phil","element":"Water","hairColor":"White","type":"Human","hp":"80","atk":"80","def":"80","spd":"80","talents":"","notes":""},
    {"name":"Pickle","element":"Dark","hairColor":"None","type":"Human","hp":"85","atk":"97","def":"68","spd":"82","talents":"","notes":""},
    {"name":"Pochita","element":"Neutral","hairColor":"Orange","type":"Non-Human","hp":"75","atk":"95","def":"95","spd":"72","talents":"","notes":""},
    {"name":"Ponyo","element":"Water","hairColor":"Red/Orange","type":"Non-Human","hp":"105","atk":"60","def":"100","spd":"80","talents":"","notes":""},
    {"name":"Power","element":"Neutral","hairColor":"Blonde/Pink","type":"Non-Human","hp":"73","atk":"92","def":"86","spd":"82","talents":"","notes":""},
    {"name":"Priestess","element":"Light","hairColor":"Blonde","type":"Human","hp":"85","atk":"85","def":"85","spd":"70","talents":"","notes":""},
    {"name":"Prince Diamond","element":"Light","hairColor":"White/Silver","type":"Human","hp":"80","atk":"92","def":"75","spd":"74","talents":"","notes":""},
    {"name":"Professor Oak","element":"Water","hairColor":"Gray","type":"Human","hp":"102","atk":"80","def":"80","spd":"75","talents":"","notes":""},
    {"name":"Puck","element":"Water","hairColor":"Gray (Fur)","type":"Non-Human","hp":"70","atk":"90","def":"78","spd":"89","talents":"","notes":""},
    {"name":"Rabo","element":"Dark","hairColor":"Brown","type":"Non-Human","hp":"85","atk":"92","def":"78","spd":"71","talents":"","notes":""},
    {"name":"Rachel","element":"Dark","hairColor":"Blonde","type":"Human","hp":"75","atk":"79","def":"84","spd":"88","talents":"","notes":""},
    {"name":"Ravel Phenex","element":"Neutral","hairColor":"Blonde","type":"Non-Human","hp":"70","atk":"80","def":"90","spd":"90","talents":"","notes":""},
    {"name":"Rayne Ames","element":"Water","hairColor":"Pink","type":"Human","hp":"84","atk":"97","def":"77","spd":"78","talents":"","notes":""},
    {"name":"Rebecca","element":"Dark","hairColor":"Brown","type":"Human","hp":"86","atk":"83","def":"78","spd":"81","talents":"","notes":""},
    {"name":"Reborn","element":"Neutral","hairColor":"Black","type":"Human","hp":"73","atk":"94","def":"76","spd":"76","talents":"","notes":""},
    {"name":"Rei Ayanami","element":"Light","hairColor":"Blue","type":"Human","hp":"80","atk":"91","def":"85","spd":"71","talents":"","notes":""},
    {"name":"Reimu Hakurei","element":"Water","hairColor":"Brown","type":"Human","hp":"89","atk":"70","def":"84","spd":"85","talents":"","notes":""},
    {"name":"Rem","element":"Dark","hairColor":"Blue","type":"Human","hp":"85","atk":"87","def":"78","spd":"71","talents":"","notes":""},
    {"name":"Rem (Death Note)","element":"Light","hairColor":"None","type":"Non-Human","hp":"86","atk":"94","def":"87","spd":"68","talents":"","notes":""},
    {"name":"Remi Ayasaki","element":"Light","hairColor":"Brown","type":"Human","hp":"75","atk":"92","def":"70","spd":"98","talents":"","notes":""},
    {"name":"Ren Amaki","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"82","atk":"84","def":"70","spd":"91","talents":"","notes":""},
    {"name":"Rena Minami","element":"Water","hairColor":"Blue","type":"Human","hp":"79","atk":"85","def":"68","spd":"94","talents":"","notes":""},
    {"name":"Ren Hakuryuu","element":"Dark","hairColor":"Black","type":"Human","hp":"84","atk":"87","def":"68","spd":"84","talents":"","notes":""},
    {"name":"Reno Ichikawa","element":"Light","hairColor":"Green","type":"Human","hp":"88","atk":"84","def":"84","spd":"84","talents":"","notes":""},
    {"name":"Rikka Takanashi","element":"Light","hairColor":"Black","type":"Human","hp":"81","atk":"90","def":"70","spd":"92","talents":"","notes":""},
    {"name":"Rimuru Tempest","element":"Dark","hairColor":"Blue","type":"Non-Human","hp":"67","atk":"102","def":"76","spd":"79","talents":"","notes":""},
    {"name":"Rintarou Okabe","element":"Light","hairColor":"Brown","type":"Human","hp":"85","atk":"90","def":"86","spd":"60","talents":"","notes":""},
    {"name":"Ririka Momobami","element":"Water","hairColor":"Silver/White","type":"Human","hp":"77","atk":"67","def":"93","spd":"80","talents":"","notes":""},
    {"name":"Ritsu Kageyama","element":"Dark","hairColor":"Black","type":"Human","hp":"78","atk":"93","def":"85","spd":"70","talents":"","notes":""},
    {"name":"Ritsu Tainaka","element":"Dark","hairColor":"Brown","type":"Human","hp":"76","atk":"88","def":"60","spd":"96","talents":"","notes":""},
    {"name":"Rize Kamishiro","element":"Light","hairColor":"Purple","type":"Non-Human","hp":"99","atk":"98","def":"70","spd":"70","talents":"","notes":""},
    {"name":"Rize Tedeza","element":"Dark","hairColor":"Blue","type":"Human","hp":"93","atk":"86","def":"76","spd":"69","talents":"","notes":""},
    {"name":"Rossweisse","element":"Neutral","hairColor":"Silver","type":"Non-Human","hp":"74","atk":"72","def":"90","spd":"93","talents":"","notes":""},
    {"name":"Roxy Migurdia","element":"Dark","hairColor":"Blue","type":"Human","hp":"70","atk":"72","def":"96","spd":"90","talents":"","notes":""},
    {"name":"Ruby Rose","element":"Neutral","hairColor":"Black/Red","type":"Human","hp":"84","atk":"90","def":"79","spd":"83","talents":"","notes":""},
    {"name":"Rudeus Greyrat","element":"Water","hairColor":"Brown","type":"Human","hp":"96","atk":"81","def":"69","spd":"82","talents":"","notes":""},
    {"name":"Rukia Kuchiki","element":"Light","hairColor":"Black","type":"Human","hp":"97","atk":"75","def":"65","spd":"83","talents":"","notes":""},
    {"name":"Ryoji Kaji","element":"Water","hairColor":"Brown","type":"Human","hp":"70","atk":"80","def":"90","spd":"89","talents":"","notes":""},
    {"name":"Ryo Kurokiba","element":"Water","hairColor":"Silver/White","type":"Human","hp":"78","atk":"85","def":"92","spd":"70","talents":"","notes":""},
    {"name":"Ryota Suzui","element":"Water","hairColor":"Brown","type":"Human","hp":"78","atk":"87","def":"87","spd":"78","talents":"","notes":""},
    {"name":"Ryo Yamada","element":"Dark","hairColor":"Blue","type":"Human","hp":"72","atk":"99","def":"70","spd":"99","talents":"","notes":""},
    {"name":"Ryuk","element":"Light","hairColor":"None","type":"Non-Human","hp":"83","atk":"100","def":"82","spd":"86","talents":"","notes":""},
    {"name":"Ryunosuke Minakata","element":"Dark","hairColor":"Black","type":"Human","hp":"82","atk":"83","def":"90","spd":"86","talents":"","notes":""},
    {"name":"Ryusui Nanami","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"92","atk":"70","def":"90","spd":"79","talents":"","notes":""},
    {"name":"Sae Itoshi","element":"Light","hairColor":"Brown/Red","type":"Human","hp":"90","atk":"90","def":"73","spd":"80","talents":"","notes":""},
    {"name":"Saika Totsuka","element":"Neutral","hairColor":"Gray/Silver","type":"Human","hp":"73","atk":"93","def":"84","spd":"78","talents":"","notes":""},
    {"name":"Saitama","element":"Dark","hairColor":"Bald","type":"Human","hp":"66","atk":"103","def":"80","spd":"68","talents":"","notes":""},
    {"name":"Sakura Haruno","element":"Neutral","hairColor":"Pink","type":"Human","hp":"85","atk":"71","def":"76","spd":"90","talents":"","notes":""},
    {"name":"Sakura Matou","element":"Water","hairColor":"Purple","type":"Human","hp":"96","atk":"68","def":"77","spd":"79","talents":"","notes":""},
    {"name":"Sally","element":"Neutral","hairColor":"Brown","type":"Human","hp":"73","atk":"94","def":"83","spd":"76","talents":"","notes":""},
    {"name":"San","element":"Dark","hairColor":"Black","type":"Human","hp":"83","atk":"105","def":"76","spd":"75","talents":"","notes":""},
    {"name":"Sans","element":"Water","hairColor":"None","type":"Non-Human","hp":"80","atk":"83","def":"72","spd":"97","talents":"","notes":""},
    {"name":"Sasaki Kojiro","element":"Dark","hairColor":"Black","type":"Human","hp":"91","atk":"91","def":"77","spd":"80","talents":"","notes":""},
    {"name":"Sasuke Uchiha","element":"Light","hairColor":"Black","type":"Human","hp":"89","atk":"80","def":"83","spd":"75","talents":"","notes":""},
    {"name":"Satoshi Isshiki","element":"Water","hairColor":"Brown","type":"Human","hp":"82","atk":"83","def":"70","spd":"87","talents":"","notes":""},
    {"name":"Satsuki Kiryuin","element":"Water","hairColor":"Black","type":"Human","hp":"93","atk":"83","def":"81","spd":"64","talents":"","notes":""},
    {"name":"Satsuki Momoi","element":"Water","hairColor":"Pink","type":"Human","hp":"96","atk":"85","def":"85","spd":"70","talents":"","notes":""},
    {"name":"Sayaka Maizono","element":"Neutral","hairColor":"Blue","type":"Human","hp":"78","atk":"68","def":"90","spd":"92","talents":"","notes":""},
    {"name":"Sayaka Miki","element":"Neutral","hairColor":"Blue","type":"Human","hp":"84","atk":"63","def":"90","spd":"82","talents":"","notes":""},
    {"name":"Sayori","element":"Dark","hairColor":"Pink","type":"Human","hp":"80","atk":"72","def":"92","spd":"81","talents":"","notes":""},
    {"name":"Sebas Tian","element":"Water","hairColor":"Black","type":"Non-Human","hp":"77","atk":"82","def":"90","spd":"74","talents":"","notes":""},
    {"name":"Seika Ijichi","element":"Dark","hairColor":"Black","type":"Human","hp":"85","atk":"95","def":"95","spd":"85","talents":"","notes":""},
    {"name":"Sephiroth","element":"Water","hairColor":"Silver/White","type":"Human","hp":"81","atk":"94","def":"73","spd":"85","talents":"","notes":""},
    {"name":"Serena","element":"Dark","hairColor":"Brown","type":"Human","hp":"95","atk":"79","def":"80","spd":"86","talents":"","notes":""},
    {"name":"Serie","element":"Water","hairColor":"Green","type":"Non-Human","hp":"90","atk":"100","def":"70","spd":"80","talents":"","notes":""},
    {"name":"Serpico","element":"Dark","hairColor":"Black","type":"Human","hp":"80","atk":"87","def":"68","spd":"96","talents":"","notes":""},
    {"name":"Serpoians","element":"Dark","hairColor":"None","type":"Non-Human","hp":"83","atk":"74","def":"105","spd":"77","talents":"","notes":""},
    {"name":"Sesshomaru","element":"Neutral","hairColor":"White/Silver","type":"Non-Human","hp":"88","atk":"71","def":"99","spd":"62","talents":"","notes":""},
    {"name":"Shalltear Bloodfallen","element":"Neutral","hairColor":"Silver/Pink","type":"Non-Human","hp":"100","atk":"67","def":"93","spd":"63","talents":"","notes":""},
    {"name":"Shea Haulia","element":"Neutral","hairColor":"Blue","type":"Non-Human","hp":"64","atk":"90","def":"63","spd":"93","talents":"","notes":""},
    {"name":"Sheele","element":"Light","hairColor":"Purple","type":"Human","hp":"90","atk":"110","def":"80","spd":"95","talents":"","notes":""},
    {"name":"Shido Itsuka","element":"Dark","hairColor":"Black","type":"Human","hp":"86","atk":"64","def":"83","spd":"92","talents":"","notes":""},
    {"name":"Shigeo Kageyama","element":"Water","hairColor":"Black","type":"Human","hp":"85","atk":"81","def":"80","spd":"86","talents":"","notes":""},
    {"name":"Shinji Ikari","element":"Dark","hairColor":"Brown","type":"Human","hp":"90","atk":"76","def":"76","spd":"90","talents":"","notes":""},
    {"name":"Shinoa Hiragi","element":"Neutral","hairColor":"Purple","type":"Human","hp":"85","atk":"97","def":"74","spd":"69","talents":"","notes":""},
    {"name":"Shinra Kishitani","element":"Neutral","hairColor":"Black","type":"Human","hp":"87","atk":"80","def":"92","spd":"81","talents":"","notes":""},
    {"name":"Shinya Kogami","element":"Light","hairColor":"Black","type":"Human","hp":"100","atk":"67","def":"83","spd":"80","talents":"","notes":""},
    {"name":"Shirai Kuroko","element":"Neutral","hairColor":"Brown","type":"Human","hp":"73","atk":"89","def":"72","spd":"89","talents":"","notes":""},
    {"name":"Shiro","element":"Light","hairColor":"White/Silver","type":"Human","hp":"82","atk":"96","def":"80","spd":"66","talents":"","notes":""},
    {"name":"Shizuku Murasaki","element":"Neutral","hairColor":"Black","type":"Human","hp":"83","atk":"93","def":"90","spd":"74","talents":"","notes":""},
    {"name":"Shizuo Heiwajima","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"85","atk":"84","def":"80","spd":"81","talents":"","notes":""},
    {"name":"Shogo Makishima","element":"Water","hairColor":"Black","type":"Human","hp":"95","atk":"76","def":"70","spd":"88","talents":"","notes":""},
    {"name":"Shokuhou Misaki","element":"Light","hairColor":"Blonde","type":"Human","hp":"78","atk":"93","def":"81","spd":"71","talents":"","notes":""},
    {"name":"Sho Suzuki","element":"Neutral","hairColor":"Black","type":"Human","hp":"68","atk":"95","def":"68","spd":"97","talents":"","notes":""},
    {"name":"Shoto Todoroki","element":"Light","hairColor":"Red/White","type":"Human","hp":"96","atk":"84","def":"75","spd":"64","talents":"","notes":""},
    {"name":"Shoyo Hinata","element":"Light","hairColor":"Orange","type":"Human","hp":"70","atk":"89","def":"72","spd":"102","talents":"","notes":""},
    {"name":"Shrek","element":"Water","hairColor":"None","type":"Non-Human","hp":"80","atk":"88","def":"75","spd":"95","talents":"","notes":""},
    {"name":"Shuji Hanma","element":"Light","hairColor":"Black","type":"Human","hp":"83","atk":"87","def":"89","spd":"77","talents":"","notes":""},
    {"name":"Shuna","element":"Water","hairColor":"Pink","type":"Non-Human","hp":"89","atk":"72","def":"93","spd":"80","talents":"","notes":""},
    {"name":"Silverash","element":"Dark","hairColor":"White/Silver","type":"Human","hp":"85","atk":"94","def":"78","spd":"81","talents":"","notes":""},
    {"name":"Sinon","element":"Neutral","hairColor":"Blue","type":"Human","hp":"74","atk":"87","def":"75","spd":"90","talents":"","notes":""},
    {"name":"Skadi","element":"Neutral","hairColor":"Red","type":"Non-Human","hp":"92","atk":"88","def":"80","spd":"80","talents":"","notes":""},
    {"name":"Skeleton","element":"Light","hairColor":"None","type":"Non-Human","hp":"75","atk":"75","def":"75","spd":"75","talents":"","notes":""},
    {"name":"Snake","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"82","atk":"90","def":"98","spd":"70","talents":"","notes":""},
    {"name":"Snorlax","element":"Dark","hairColor":"Blue/Black","type":"Non-Human","hp":"99","atk":"70","def":"99","spd":"70","talents":"","notes":""},
    {"name":"Snowy Owl","element":"Dark","hairColor":"White","type":"Non-Human","hp":"81","atk":"88","def":"72","spd":"97","talents":"","notes":""},
    {"name":"Sora (Kingdom Hearts)","element":"Water","hairColor":"Brown","type":"Human","hp":"92","atk":"96","def":"88","spd":"62","talents":"","notes":""},
    {"name":"Soshiro Hoshina","element":"Light","hairColor":"Purple","type":"Human","hp":"84","atk":"81","def":"79","spd":"96","talents":"","notes":""},
    {"name":"Sosuke Aizen","element":"Dark","hairColor":"Brown","type":"Human","hp":"81","atk":"92","def":"73","spd":"80","talents":"","notes":""},
    {"name":"Souei","element":"Neutral","hairColor":"Silver/White","type":"Non-Human","hp":"74","atk":"80","def":"80","spd":"90","talents":"","notes":""},
    {"name":"Soul Evans","element":"Water","hairColor":"White","type":"Human","hp":"65","atk":"85","def":"85","spd":"91","talents":"","notes":""},
    {"name":"Spectral Wraith","element":"Water","hairColor":"None","type":"Non-Human","hp":"80","atk":"90","def":"70","spd":"90","talents":"","notes":""},
    {"name":"Spike Spiegel","element":"Dark","hairColor":"Green","type":"Human","hp":"81","atk":"98","def":"71","spd":"80","talents":"","notes":""},
    {"name":"Squalo","element":"Dark","hairColor":"Silver/White","type":"Human","hp":"86","atk":"82","def":"86","spd":"76","talents":"","notes":""},
    {"name":"Squirtle","element":"Light","hairColor":"None","type":"Non-Human","hp":"81","atk":"92","def":"83","spd":"75","talents":"","notes":""},
    {"name":"Statue Of God","element":"Dark","hairColor":"None","type":"Non-Human","hp":"100","atk":"95","def":"95","spd":"100","talents":"","notes":""},
    {"name":"Staz C Blood","element":"Light","hairColor":"Black","type":"Non-Human","hp":"90","atk":"87","def":"80","spd":"64","talents":"","notes":""},
    {"name":"Stephanie Dola","element":"Dark","hairColor":"Red/Pink","type":"Human","hp":"86","atk":"72","def":"96","spd":"70","talents":"","notes":""},
    {"name":"Subaru Natsuki","element":"Neutral","hairColor":"Black","type":"Human","hp":"82","atk":"80","def":"80","spd":"80","talents":"","notes":""},
    {"name":"Su Mucheng","element":"Light","hairColor":"Orange","type":"Human","hp":"84","atk":"88","def":"78","spd":"90","talents":"","notes":""},
    {"name":"Sung Jinwoo","element":"Neutral","hairColor":"Black","type":"Human","hp":"85","atk":"93","def":"68","spd":"94","talents":"","notes":""},
    {"name":"Suou Pavlichenko","element":"Light","hairColor":"Silver/White","type":"Human","hp":"76","atk":"97","def":"75","spd":"83","talents":"","notes":""},
    {"name":"Superman","element":"Light","hairColor":"Black","type":"Non-Human","hp":"72","atk":"107","def":"72","spd":"89","talents":"","notes":""},
    {"name":"Suzaku Kururugi","element":"Water","hairColor":"Brown","type":"Human","hp":"83","atk":"79","def":"71","spd":"87","talents":"","notes":""},
    {"name":"Suzuha Amane","element":"Light","hairColor":"Red","type":"Human","hp":"76","atk":"92","def":"70","spd":"88","talents":"","notes":""},
    {"name":"Suzune Horikita","element":"Water","hairColor":"Black","type":"Human","hp":"85","atk":"71","def":"92","spd":"83","talents":"","notes":""},
    {"name":"Suzuya Juuzou","element":"Dark","hairColor":"White","type":"Human","hp":"72","atk":"66","def":"94","spd":"90","talents":"","notes":""},
    {"name":"Sverkel","element":"Neutral","hairColor":"Gray/White","type":"Human","hp":"80","atk":"70","def":"65","spd":"91","talents":"","notes":""},
    {"name":"Sword Maiden","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"75","atk":"84","def":"70","spd":"96","talents":"","notes":""},
    {"name":"Sypha Belnades","element":"Light","hairColor":"Blonde","type":"Human","hp":"91","atk":"90","def":"80","spd":"75","talents":"","notes":""},
    {"name":"Takashi Mitsuya","element":"Neutral","hairColor":"Purple","type":"Human","hp":"80","atk":"72","def":"95","spd":"85","talents":"","notes":""},
    {"name":"Takasugi Shinsuke","element":"Dark","hairColor":"Purple","type":"Human","hp":"80","atk":"84","def":"75","spd":"88","talents":"","notes":""},
    {"name":"Takemichi Hanagaki","element":"Dark","hairColor":"Blonde","type":"Human","hp":"85","atk":"78","def":"79","spd":"87","talents":"","notes":""},
    {"name":"Takeshi Yamamoto","element":"Water","hairColor":"Black","type":"Human","hp":"78","atk":"101","def":"76","spd":"65","talents":"","notes":""},
    {"name":"Taki Tachibana","element":"Light","hairColor":"Black","type":"Human","hp":"78","atk":"92","def":"81","spd":"89","talents":"","notes":""},
    {"name":"Takumi Aldini","element":"Dark","hairColor":"Blonde","type":"Human","hp":"78","atk":"84","def":"70","spd":"92","talents":"","notes":""},
    {"name":"Tamiya Gantetsusai","element":"Neutral","hairColor":"Black","type":"Human","hp":"90","atk":"87","def":"80","spd":"70","talents":"","notes":""},
    {"name":"Tanjiro Kamado","element":"Water","hairColor":"Black/Red","type":"Human","hp":"80","atk":"82","def":"77","spd":"89","talents":"","notes":""},
    {"name":"Tatsumi","element":"Water","hairColor":"Brown","type":"Human","hp":"87","atk":"78","def":"78","spd":"87","talents":"","notes":""},
    {"name":"Tatsuya Shiba","element":"Dark","hairColor":"Black","type":"Human","hp":"85","atk":"92","def":"78","spd":"80","talents":"","notes":""},
    {"name":"Teppei Kiyoshi","element":"Dark","hairColor":"Brown","type":"Human","hp":"70","atk":"95","def":"95","spd":"70","talents":"","notes":""},
    {"name":"Teruki Hanazawa","element":"Light","hairColor":"Blonde","type":"Human","hp":"77","atk":"87","def":"80","spd":"83","talents":"","notes":""},
    {"name":"Tet","element":"Dark","hairColor":"Rainbow","type":"Non-Human","hp":"82","atk":"84","def":"83","spd":"78","talents":"","notes":""},
    {"name":"Tetsuro Kuroo","element":"Light","hairColor":"Black","type":"Human","hp":"90","atk":"79","def":"81","spd":"74","talents":"","notes":""},
    {"name":"Tetsuya Kuroko","element":"Dark","hairColor":"Blue","type":"Human","hp":"100","atk":"71","def":"96","spd":"70","talents":"","notes":""},
    {"name":"Texas","element":"Neutral","hairColor":"Black","type":"Non-Human","hp":"78","atk":"76","def":"92","spd":"94","talents":"","notes":""},
    {"name":"Thorfinn","element":"Light","hairColor":"Blonde","type":"Human","hp":"85","atk":"100","def":"65","spd":"90","talents":"","notes":""},
    {"name":"Thorkell","element":"Dark","hairColor":"Blonde","type":"Human","hp":"92","atk":"92","def":"95","spd":"85","talents":"","notes":""},
    {"name":"Tifa Lockhart","element":"Neutral","hairColor":"Black","type":"Human","hp":"82","atk":"96","def":"64","spd":"98","talents":"","notes":""},
    {"name":"Tio Klarus","element":"Water","hairColor":"Blue","type":"Non-Human","hp":"96","atk":"82","def":"88","spd":"58","talents":"","notes":""},
    {"name":"Toge Inumaki","element":"Dark","hairColor":"White","type":"Human","hp":"86","atk":"89","def":"73","spd":"81","talents":"","notes":""},
    {"name":"Tohka Yatogami","element":"Light","hairColor":"Purple","type":"Human","hp":"65","atk":"92","def":"99","spd":"62","talents":"","notes":""},
    {"name":"Toji Fushiguro","element":"Neutral","hairColor":"Black","type":"Human","hp":"92","atk":"97","def":"98","spd":"93","talents":"","notes":""},
    {"name":"Toko Fukawa","element":"Light","hairColor":"Purple","type":"Human","hp":"78","atk":"77","def":"80","spd":"94","talents":"","notes":""},
    {"name":"Tooru Oikawa","element":"Dark","hairColor":"Brown","type":"Human","hp":"83","atk":"91","def":"70","spd":"91","talents":"","notes":""},
    {"name":"Toru Ishikawa","element":"Neutral","hairColor":"Brown","type":"Human","hp":"73","atk":"90","def":"93","spd":"75","talents":"","notes":""},
    {"name":"Toshiro Hitsugaya","element":"Water","hairColor":"White","type":"Human","hp":"91","atk":"80","def":"89","spd":"60","talents":"","notes":""},
    {"name":"Totoro","element":"Light","hairColor":"Gray","type":"Non-Human","hp":"92","atk":"83","def":"85","spd":"73","talents":"","notes":""},
    {"name":"Touka Kirishima","element":"Dark","hairColor":"Purple/Blue","type":"Non-Human","hp":"75","atk":"83","def":"84","spd":"86","talents":"","notes":""},
    {"name":"Trafalgar D Law","element":"Water","hairColor":"Black","type":"Human","hp":"87","atk":"74","def":"81","spd":"80","talents":"","notes":""},
    {"name":"Trevor Belmont","element":"Water","hairColor":"Brown","type":"Human","hp":"85","atk":"88","def":"90","spd":"75","talents":"","notes":""},
    {"name":"Trissy (Tris)","element":"Water","hairColor":"Black","type":"Human","hp":"70","atk":"100","def":"70","spd":"100","talents":"","notes":""},
    {"name":"Trixx","element":"Water","hairColor":"Orange","type":"Non-Human","hp":"99","atk":"95","def":"78","spd":"68","talents":"","notes":""},
    {"name":"Tsubaki Kasugano","element":"Dark","hairColor":"Black","type":"Human","hp":"67","atk":"88","def":"77","spd":"89","talents":"","notes":""},
    {"name":"Tsumugi Kotobuki","element":"Water","hairColor":"Blonde","type":"Human","hp":"72","atk":"77","def":"85","spd":"91","talents":"","notes":""},
    {"name":"Tsuyu Asui (Froppy)","element":"Water","hairColor":"Green","type":"Human","hp":"79","atk":"82","def":"80","spd":"96","talents":"","notes":""},
    {"name":"Turbo Granny","element":"Dark","hairColor":"Gray/White","type":"Non-Human","hp":"60","atk":"100","def":"97","spd":"85","talents":"","notes":""},
    {"name":"Tushan Susu","element":"Dark","hairColor":"Red","type":"Non-Human","hp":"91","atk":"83","def":"83","spd":"82","talents":"","notes":""},
    {"name":"Twenty Fifth Bam","element":"Dark","hairColor":"Brown","type":"Human","hp":"78","atk":"88","def":"78","spd":"88","talents":"","notes":""},
    {"name":"Ubel","element":"Light","hairColor":"Green","type":"Human","hp":"90","atk":"85","def":"85","spd":"80","talents":"","notes":""},
    {"name":"Ulquiorra Schiffer","element":"Water","hairColor":"Black","type":"Non-Human","hp":"82","atk":"92","def":"79","spd":"65","talents":"","notes":""},
    {"name":"Uran","element":"Dark","hairColor":"Brown","type":"Non-Human","hp":"89","atk":"74","def":"77","spd":"94","talents":"","notes":""},
    {"name":"Usagi Tsukino (Sailor Moon)","element":"Water","hairColor":"Blonde","type":"Human","hp":"94","atk":"79","def":"61","spd":"91","talents":"","notes":""},
    {"name":"Ushio Kofune","element":"Water","hairColor":"Black","type":"Human","hp":"83","atk":"75","def":"80","spd":"99","talents":"","notes":""},
    {"name":"Usopp","element":"Neutral","hairColor":"Black","type":"Human","hp":"70","atk":"74","def":"86","spd":"93","talents":"","notes":""},
    {"name":"Uta","element":"Dark","hairColor":"Purple","type":"Non-Human","hp":"89","atk":"68","def":"89","spd":"94","talents":"","notes":""},
    {"name":"Vi","element":"Water","hairColor":"Pink","type":"Human","hp":"93","atk":"80","def":"85","spd":"78","talents":"","notes":""},
    {"name":"Vicious","element":"Light","hairColor":"White/Silver","type":"Human","hp":"90","atk":"90","def":"70","spd":"75","talents":"","notes":""},
    {"name":"Vlad Tepes (Dracula)","element":"Water","hairColor":"Black","type":"Non-Human","hp":"88","atk":"95","def":"65","spd":"90","talents":"","notes":""},
    {"name":"Vorona","element":"Neutral","hairColor":"White/Silver","type":"Human","hp":"101","atk":"83","def":"102","spd":"70","talents":"","notes":""},
    {"name":"V.V.","element":"Dark","hairColor":"Blonde","type":"Human","hp":"83","atk":"82","def":"80","spd":"85","talents":"","notes":""},
    {"name":"Wakana Gojo","element":"Neutral","hairColor":"Black","type":"Human","hp":"78","atk":"90","def":"75","spd":"95","talents":"","notes":""},
    {"name":"Wave","element":"Dark","hairColor":"Blue","type":"Human","hp":"75","atk":"92","def":"71","spd":"88","talents":"","notes":""},
    {"name":"Weiss Schnee","element":"Dark","hairColor":"White","type":"Human","hp":"84","atk":"80","def":"72","spd":"97","talents":"","notes":""},
    {"name":"Wendy Marvell","element":"Dark","hairColor":"Blue","type":"Human","hp":"61","atk":"92","def":"80","spd":"89","talents":"","notes":""},
    {"name":"Winter Elf","element":"Dark","hairColor":"White/Silver","type":"Non-Human","hp":"94","atk":"92","def":"70","spd":"85","talents":"","notes":""},
    {"name":"Winter Frost","element":"Water","hairColor":"White/Blue","type":"Non-Human","hp":"98","atk":"74","def":"83","spd":"82","talents":"","notes":""},
    {"name":"Witch Of The Waste","element":"Water","hairColor":"Gray","type":"Non-Human","hp":"86","atk":"77","def":"77","spd":"80","talents":"","notes":""},
    {"name":"Wiz","element":"Water","hairColor":"Blue","type":"Non-Human","hp":"85","atk":"72","def":"85","spd":"88","talents":"","notes":""},
    {"name":"Wolf","element":"Light","hairColor":"Black","type":"Non-Human","hp":"70","atk":"89","def":"81","spd":"86","talents":"","notes":""},
    {"name":"Xenovia Quarta","element":"Water","hairColor":"Blue","type":"Human","hp":"80","atk":"85","def":"95","spd":"65","talents":"","notes":""},
    {"name":"Yachiyo Nanami","element":"Water","hairColor":"Black","type":"Human","hp":"80","atk":"81","def":"83","spd":"81","talents":"","notes":""},
    {"name":"Yakumo Oomori (Jason)","element":"Dark","hairColor":"White","type":"Non-Human","hp":"70","atk":"83","def":"93","spd":"88","talents":"","notes":""},
    {"name":"Yamada Asaemon Sagiri","element":"Water","hairColor":"Black","type":"Human","hp":"75","atk":"101","def":"70","spd":"90","talents":"","notes":""},
    {"name":"Yamada Asaemon Senta","element":"Neutral","hairColor":"Black","type":"Human","hp":"95","atk":"97","def":"102","spd":"85","talents":"","notes":""},
    {"name":"Yamada Asaemon Shion","element":"Light","hairColor":"Black","type":"Human","hp":"74","atk":"92","def":"65","spd":"98","talents":"","notes":""},
    {"name":"Yami Sukehiro","element":"Water","hairColor":"Black","type":"Human","hp":"98","atk":"105","def":"71","spd":"82","talents":"","notes":""},
    {"name":"Yato","element":"Dark","hairColor":"Black","type":"Non-Human","hp":"76","atk":"85","def":"82","spd":"80","talents":"","notes":""},
    {"name":"Ye Xiu","element":"Light","hairColor":"Black","type":"Human","hp":"95","atk":"87","def":"70","spd":"87","talents":"","notes":""},
    {"name":"Yhwach","element":"Neutral","hairColor":"Black","type":"Human","hp":"86","atk":"77","def":"92","spd":"75","talents":"","notes":""},
    {"name":"Yin","element":"Dark","hairColor":"Silver","type":"Non-Human","hp":"86","atk":"88","def":"68","spd":"77","talents":"","notes":""},
    {"name":"Yoh Asakura","element":"Dark","hairColor":"Brown","type":"Human","hp":"85","atk":"92","def":"80","spd":"70","talents":"","notes":""},
    {"name":"Yoichi Nagumo","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"82","atk":"78","def":"95","spd":"82","talents":"","notes":""},
    {"name":"Yoo Jinho","element":"Neutral","hairColor":"Blonde","type":"Human","hp":"80","atk":"78","def":"100","spd":"68","talents":"","notes":""},
    {"name":"Yor Forger","element":"Dark","hairColor":"Black","type":"Human","hp":"70","atk":"98","def":"82","spd":"80","talents":"","notes":""},
    {"name":"Yoshino","element":"Water","hairColor":"Blue","type":"Human","hp":"83","atk":"82","def":"81","spd":"80","talents":"","notes":""},
    {"name":"Yue","element":"Neutral","hairColor":"Blonde","type":"Non-Human","hp":"76","atk":"83","def":"104","spd":"68","talents":"","notes":""},
    {"name":"Yugo","element":"Neutral","hairColor":"Green","type":"Human","hp":"73","atk":"98","def":"62","spd":"95","talents":"","notes":""},
    {"name":"Yui","element":"Light","hairColor":"Pink","type":"Human","hp":"84","atk":"72","def":"76","spd":"100","talents":"","notes":""},
    {"name":"Yui Hirasawa","element":"Dark","hairColor":"Brown","type":"Human","hp":"67","atk":"94","def":"71","spd":"86","talents":"","notes":""},
    {"name":"Yu Ishigami","element":"Water","hairColor":"Black","type":"Human","hp":"72","atk":"92","def":"80","spd":"83","talents":"","notes":""},
    {"name":"Yujiro Hanma","element":"Dark","hairColor":"Black/Red","type":"Human","hp":"70","atk":"97","def":"84","spd":"81","talents":"","notes":""},
    {"name":"Yukichi Fukuzawa","element":"Neutral","hairColor":"Gray/Silver","type":"Human","hp":"89","atk":"94","def":"65","spd":"77","talents":"","notes":""},
    {"name":"Yukina","element":"Neutral","hairColor":"Teal","type":"Non-Human","hp":"83","atk":"92","def":"77","spd":"80","talents":"","notes":""},
    {"name":"Yukine","element":"Light","hairColor":"Blonde","type":"Non-Human","hp":"74","atk":"83","def":"90","spd":"76","talents":"","notes":""},
    {"name":"Yuki Nonaka","element":"Neutral","hairColor":"Silver/White","type":"Human","hp":"83","atk":"84","def":"76","spd":"83","talents":"","notes":""},
    {"name":"Yukio Okumura","element":"Light","hairColor":"Black","type":"Human","hp":"71","atk":"95","def":"74","spd":"85","talents":"","notes":""},
    {"name":"Yuki Sumi","element":"Water","hairColor":"Brown","type":"Human","hp":"83","atk":"79","def":"93","spd":"77","talents":"","notes":""},
    {"name":"Yukiteru Amano","element":"Water","hairColor":"Black","type":"Human","hp":"98","atk":"66","def":"100","spd":"64","talents":"","notes":""},
    {"name":"Yumeko Jabami","element":"Water","hairColor":"Black","type":"Human","hp":"60","atk":"90","def":"90","spd":"90","talents":"","notes":""},
    {"name":"Yuno Gasai","element":"Light","hairColor":"Pink","type":"Human","hp":"75","atk":"90","def":"83","spd":"70","talents":"","notes":""},
    {"name":"Yunyun","element":"Neutral","hairColor":"Silver/White","type":"Human","hp":"72","atk":"93","def":"91","spd":"69","talents":"","notes":""},
    {"name":"Yuri","element":"Light","hairColor":"Purple","type":"Human","hp":"78","atk":"87","def":"85","spd":"75","talents":"","notes":""},
    {"name":"Yuri Briar","element":"Neutral","hairColor":"Black","type":"Human","hp":"95","atk":"67","def":"90","spd":"75","talents":"","notes":""},
    {"name":"Yuri Nakamura","element":"Dark","hairColor":"Pink/Purple","type":"Human","hp":"73","atk":"85","def":"82","spd":"87","talents":"","notes":""},
    {"name":"Yuta Okkotsu","element":"Dark","hairColor":"Black","type":"Human","hp":"85","atk":"93","def":"73","spd":"76","talents":"","notes":""},
    {"name":"Yuuto Kiba","element":"Water","hairColor":"Blonde","type":"Human","hp":"60","atk":"95","def":"75","spd":"95","talents":"","notes":""},
    {"name":"Yuzuriha","element":"Dark","hairColor":"Black","type":"Human","hp":"81","atk":"82","def":"95","spd":"75","talents":"","notes":""},
    {"name":"Yuzuru Otonashi","element":"Neutral","hairColor":"Brown","type":"Human","hp":"85","atk":"87","def":"70","spd":"87","talents":"","notes":""},
    {"name":"Zanka Nijiku","element":"Neutral","hairColor":"Black","type":"Human","hp":"99","atk":"75","def":"95","spd":"70","talents":"","notes":""},
    {"name":"Zeke Yeager","element":"Dark","hairColor":"Blonde","type":"Human","hp":"95","atk":"80","def":"90","spd":"70","talents":"","notes":""},
    {"name":"Zelda","element":"Dark","hairColor":"Blonde","type":"Human","hp":"90","atk":"76","def":"90","spd":"80","talents":"","notes":""},
    {"name":"Zeref Dragneel","element":"Water","hairColor":"Black","type":"Human","hp":"90","atk":"78","def":"86","spd":"90","talents":"","notes":""},
    {"name":"Zero Two","element":"Neutral","hairColor":"Pink","type":"Non-Human","hp":"87","atk":"84","def":"76","spd":"79","talents":"","notes":""},
    {"name":"Zest","element":"Water","hairColor":"Silver/White","type":"Non-Human","hp":"80","atk":"71","def":"83","spd":"95","talents":"","notes":""},
    {"name":"Zeta","element":"Neutral","hairColor":"Black","type":"Human","hp":"100","atk":"70","def":"80","spd":"93","talents":"","notes":""},
    {"name":"Zombieman","element":"Light","hairColor":"Black","type":"Human","hp":"70","atk":"97","def":"69","spd":"83","talents":"","notes":""},
    {"name":"Zora Ideale","element":"Dark","hairColor":"Black/Red","type":"Human","hp":"91","atk":"95","def":"71","spd":"66","talents":"","notes":""}
];